"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AlertAck(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    class _AlertAckStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlertAckStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AlertAck._AlertAckStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ALERT_ACK_STATUS_UNSPECIFIED: AlertAck._AlertAckStatus.ValueType  # 0
        """Reason not set"""
        ALERT_ACK_STATUS_ACCEPTED: AlertAck._AlertAckStatus.ValueType  # 1
        """Alert accepted"""
        ALERT_ACK_STATUS_REJECTED: AlertAck._AlertAckStatus.ValueType  # 2
        """Alert rejected"""
        ALERT_ACK_STATUS_CANCELLED: AlertAck._AlertAckStatus.ValueType  # 3
        """Alert cancelled"""

    class AlertAckStatus(_AlertAckStatus, metaclass=_AlertAckStatusEnumTypeWrapper): ...
    ALERT_ACK_STATUS_UNSPECIFIED: AlertAck.AlertAckStatus.ValueType  # 0
    """Reason not set"""
    ALERT_ACK_STATUS_ACCEPTED: AlertAck.AlertAckStatus.ValueType  # 1
    """Alert accepted"""
    ALERT_ACK_STATUS_REJECTED: AlertAck.AlertAckStatus.ValueType  # 2
    """Alert rejected"""
    ALERT_ACK_STATUS_CANCELLED: AlertAck.AlertAckStatus.ValueType  # 3
    """Alert cancelled"""

    ALERT_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    ALERT_ACK_STATUS_FIELD_NUMBER: _builtins.int
    alert_id: _builtins.str
    """ULID for the message"""
    alert_ack_status: Global___AlertAck.AlertAckStatus.ValueType
    """State of the information in this message"""
    @_builtins.property
    def reason(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """   optional AlertStatus alert_status = 2 [(field_options) = {is_mandatory: true}]; // State of the information in this message
           optional string reason = 3; // Reason why alert was not accepted
        Reason(s) why alert was not accepted
        """

    def __init__(
        self,
        *,
        alert_id: _builtins.str | None = ...,
        reason: _abc.Iterable[_builtins.str] | None = ...,
        alert_ack_status: Global___AlertAck.AlertAckStatus.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_alert_ack_status", b"_alert_ack_status", "_alert_id", b"_alert_id", "alert_ack_status", b"alert_ack_status", "alert_id", b"alert_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_alert_ack_status", b"_alert_ack_status", "_alert_id", b"_alert_id", "alert_ack_status", b"alert_ack_status", "alert_id", b"alert_id", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__alert_ack_status: _TypeAlias = _typing.Literal["alert_ack_status"]  # noqa: Y015
    _WhichOneofArgType__alert_ack_status: _TypeAlias = _typing.Literal["_alert_ack_status", b"_alert_ack_status"]  # noqa: Y015
    _WhichOneofReturnType__alert_id: _TypeAlias = _typing.Literal["alert_id"]  # noqa: Y015
    _WhichOneofArgType__alert_id: _TypeAlias = _typing.Literal["_alert_id", b"_alert_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__alert_ack_status) -> _WhichOneofReturnType__alert_ack_status | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__alert_id) -> _WhichOneofReturnType__alert_id | None: ...

Global___AlertAck: _TypeAlias = AlertAck  # noqa: Y015
