"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sapient_msg.bsi_flex_335_v2_0 import associated_detection_pb2 as _associated_detection_pb2
from sapient_msg.bsi_flex_335_v2_0 import associated_file_pb2 as _associated_file_pb2
from sapient_msg.bsi_flex_335_v2_0 import location_pb2 as _location_pb2
from sapient_msg.bsi_flex_335_v2_0 import range_bearing_pb2 as _range_bearing_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Alert(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    class _AlertType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlertTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Alert._AlertType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ALERT_TYPE_UNSPECIFIED: Alert._AlertType.ValueType  # 0
        """Unset enum"""
        ALERT_TYPE_INFORMATION: Alert._AlertType.ValueType  # 1
        ALERT_TYPE_WARNING: Alert._AlertType.ValueType  # 2
        ALERT_TYPE_CRITICAL: Alert._AlertType.ValueType  # 3
        ALERT_TYPE_ERROR: Alert._AlertType.ValueType  # 4
        ALERT_TYPE_FATAL: Alert._AlertType.ValueType  # 5
        ALERT_TYPE_MODE_CHANGE: Alert._AlertType.ValueType  # 6

    class AlertType(_AlertType, metaclass=_AlertTypeEnumTypeWrapper): ...
    ALERT_TYPE_UNSPECIFIED: Alert.AlertType.ValueType  # 0
    """Unset enum"""
    ALERT_TYPE_INFORMATION: Alert.AlertType.ValueType  # 1
    ALERT_TYPE_WARNING: Alert.AlertType.ValueType  # 2
    ALERT_TYPE_CRITICAL: Alert.AlertType.ValueType  # 3
    ALERT_TYPE_ERROR: Alert.AlertType.ValueType  # 4
    ALERT_TYPE_FATAL: Alert.AlertType.ValueType  # 5
    ALERT_TYPE_MODE_CHANGE: Alert.AlertType.ValueType  # 6

    class _AlertStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlertStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Alert._AlertStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ALERT_STATUS_UNSPECIFIED: Alert._AlertStatus.ValueType  # 0
        """Unset enum"""
        ALERT_STATUS_ACTIVE: Alert._AlertStatus.ValueType  # 1
        ALERT_STATUS_ACKNOWLEDGE: Alert._AlertStatus.ValueType  # 2
        ALERT_STATUS_REJECT: Alert._AlertStatus.ValueType  # 3
        ALERT_STATUS_IGNORE: Alert._AlertStatus.ValueType  # 4
        ALERT_STATUS_CLEAR: Alert._AlertStatus.ValueType  # 5

    class AlertStatus(_AlertStatus, metaclass=_AlertStatusEnumTypeWrapper): ...
    ALERT_STATUS_UNSPECIFIED: Alert.AlertStatus.ValueType  # 0
    """Unset enum"""
    ALERT_STATUS_ACTIVE: Alert.AlertStatus.ValueType  # 1
    ALERT_STATUS_ACKNOWLEDGE: Alert.AlertStatus.ValueType  # 2
    ALERT_STATUS_REJECT: Alert.AlertStatus.ValueType  # 3
    ALERT_STATUS_IGNORE: Alert.AlertStatus.ValueType  # 4
    ALERT_STATUS_CLEAR: Alert.AlertStatus.ValueType  # 5

    class _DiscretePriority:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DiscretePriorityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Alert._DiscretePriority.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DISCRETE_PRIORITY_UNSPECIFIED: Alert._DiscretePriority.ValueType  # 0
        """Alert priority not set"""
        DISCRETE_PRIORITY_LOW: Alert._DiscretePriority.ValueType  # 1
        """Low alert priority"""
        DISCRETE_PRIORITY_MEDIUM: Alert._DiscretePriority.ValueType  # 2
        """Medium alert priority"""
        DISCRETE_PRIORITY_HIGH: Alert._DiscretePriority.ValueType  # 3
        """High alert priority"""

    class DiscretePriority(_DiscretePriority, metaclass=_DiscretePriorityEnumTypeWrapper): ...
    DISCRETE_PRIORITY_UNSPECIFIED: Alert.DiscretePriority.ValueType  # 0
    """Alert priority not set"""
    DISCRETE_PRIORITY_LOW: Alert.DiscretePriority.ValueType  # 1
    """Low alert priority"""
    DISCRETE_PRIORITY_MEDIUM: Alert.DiscretePriority.ValueType  # 2
    """Medium alert priority"""
    DISCRETE_PRIORITY_HIGH: Alert.DiscretePriority.ValueType  # 3
    """High alert priority"""

    ALERT_ID_FIELD_NUMBER: _builtins.int
    ALERT_TYPE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    RANGE_BEARING_FIELD_NUMBER: _builtins.int
    LOCATION_FIELD_NUMBER: _builtins.int
    REGION_ID_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    RANKING_FIELD_NUMBER: _builtins.int
    CONFIDENCE_FIELD_NUMBER: _builtins.int
    ASSOCIATED_FILE_FIELD_NUMBER: _builtins.int
    ASSOCIATED_DETECTION_FIELD_NUMBER: _builtins.int
    ADDITIONAL_INFORMATION_FIELD_NUMBER: _builtins.int
    alert_id: _builtins.str
    """ULID for the message"""
    alert_type: Global___Alert.AlertType.ValueType
    """Type of alert message"""
    status: Global___Alert.AlertStatus.ValueType
    """State of the information in this message"""
    description: _builtins.str
    """Description of the alert (normally displayed on a GUI)"""
    region_id: _builtins.str
    """ULID of the region the alert is from"""
    priority: Global___Alert.DiscretePriority.ValueType
    """Priority of the alert"""
    ranking: _builtins.float
    """0-1"""
    confidence: _builtins.float
    """Confidence (0-1) that the alert is not a false-alarm"""
    additional_information: _builtins.str
    """Any additional information that may be useful for the alert consumer"""
    @_builtins.property
    def range_bearing(self) -> _range_bearing_pb2.RangeBearing:
        """Location of the alert in Sphereical coordinates"""

    @_builtins.property
    def location(self) -> _location_pb2.Location:
        """Location of the alert in Geo coordinates"""

    @_builtins.property
    def associated_file(self) -> _containers.RepeatedCompositeFieldContainer[_associated_file_pb2.AssociatedFile]:
        """URL linking to any files associated with the alert"""

    @_builtins.property
    def associated_detection(self) -> _containers.RepeatedCompositeFieldContainer[_associated_detection_pb2.AssociatedDetection]:
        """Detections associated with the alert"""

    def __init__(
        self,
        *,
        alert_id: _builtins.str | None = ...,
        alert_type: Global___Alert.AlertType.ValueType | None = ...,
        status: Global___Alert.AlertStatus.ValueType | None = ...,
        description: _builtins.str | None = ...,
        range_bearing: _range_bearing_pb2.RangeBearing | None = ...,
        location: _location_pb2.Location | None = ...,
        region_id: _builtins.str | None = ...,
        priority: Global___Alert.DiscretePriority.ValueType | None = ...,
        ranking: _builtins.float | None = ...,
        confidence: _builtins.float | None = ...,
        associated_file: _abc.Iterable[_associated_file_pb2.AssociatedFile] | None = ...,
        associated_detection: _abc.Iterable[_associated_detection_pb2.AssociatedDetection] | None = ...,
        additional_information: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_additional_information", b"_additional_information", "_alert_id", b"_alert_id", "_alert_type", b"_alert_type", "_confidence", b"_confidence", "_description", b"_description", "_priority", b"_priority", "_ranking", b"_ranking", "_region_id", b"_region_id", "_status", b"_status", "additional_information", b"additional_information", "alert_id", b"alert_id", "alert_type", b"alert_type", "confidence", b"confidence", "description", b"description", "location", b"location", "location_oneof", b"location_oneof", "priority", b"priority", "range_bearing", b"range_bearing", "ranking", b"ranking", "region_id", b"region_id", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_additional_information", b"_additional_information", "_alert_id", b"_alert_id", "_alert_type", b"_alert_type", "_confidence", b"_confidence", "_description", b"_description", "_priority", b"_priority", "_ranking", b"_ranking", "_region_id", b"_region_id", "_status", b"_status", "additional_information", b"additional_information", "alert_id", b"alert_id", "alert_type", b"alert_type", "associated_detection", b"associated_detection", "associated_file", b"associated_file", "confidence", b"confidence", "description", b"description", "location", b"location", "location_oneof", b"location_oneof", "priority", b"priority", "range_bearing", b"range_bearing", "ranking", b"ranking", "region_id", b"region_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__additional_information: _TypeAlias = _typing.Literal["additional_information"]  # noqa: Y015
    _WhichOneofArgType__additional_information: _TypeAlias = _typing.Literal["_additional_information", b"_additional_information"]  # noqa: Y015
    _WhichOneofReturnType__alert_id: _TypeAlias = _typing.Literal["alert_id"]  # noqa: Y015
    _WhichOneofArgType__alert_id: _TypeAlias = _typing.Literal["_alert_id", b"_alert_id"]  # noqa: Y015
    _WhichOneofReturnType__alert_type: _TypeAlias = _typing.Literal["alert_type"]  # noqa: Y015
    _WhichOneofArgType__alert_type: _TypeAlias = _typing.Literal["_alert_type", b"_alert_type"]  # noqa: Y015
    _WhichOneofReturnType__confidence: _TypeAlias = _typing.Literal["confidence"]  # noqa: Y015
    _WhichOneofArgType__confidence: _TypeAlias = _typing.Literal["_confidence", b"_confidence"]  # noqa: Y015
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__priority: _TypeAlias = _typing.Literal["priority"]  # noqa: Y015
    _WhichOneofArgType__priority: _TypeAlias = _typing.Literal["_priority", b"_priority"]  # noqa: Y015
    _WhichOneofReturnType__ranking: _TypeAlias = _typing.Literal["ranking"]  # noqa: Y015
    _WhichOneofArgType__ranking: _TypeAlias = _typing.Literal["_ranking", b"_ranking"]  # noqa: Y015
    _WhichOneofReturnType__region_id: _TypeAlias = _typing.Literal["region_id"]  # noqa: Y015
    _WhichOneofArgType__region_id: _TypeAlias = _typing.Literal["_region_id", b"_region_id"]  # noqa: Y015
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    _WhichOneofReturnType_location_oneof: _TypeAlias = _typing.Literal["range_bearing", "location"]  # noqa: Y015
    _WhichOneofArgType_location_oneof: _TypeAlias = _typing.Literal["location_oneof", b"location_oneof"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__additional_information) -> _WhichOneofReturnType__additional_information | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__alert_id) -> _WhichOneofReturnType__alert_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__alert_type) -> _WhichOneofReturnType__alert_type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__confidence) -> _WhichOneofReturnType__confidence | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__priority) -> _WhichOneofReturnType__priority | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ranking) -> _WhichOneofReturnType__ranking | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__region_id) -> _WhichOneofReturnType__region_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_location_oneof) -> _WhichOneofReturnType_location_oneof | None: ...

Global___Alert: _TypeAlias = Alert  # noqa: Y015
