"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _AssociationRelation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AssociationRelationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AssociationRelation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ASSOCIATION_RELATION_UNSPECIFIED: _AssociationRelation.ValueType  # 0
    """Unset enum"""
    ASSOCIATION_RELATION_NO_RELATION: _AssociationRelation.ValueType  # 1
    ASSOCIATION_RELATION_PARENT: _AssociationRelation.ValueType  # 2
    ASSOCIATION_RELATION_CHILD: _AssociationRelation.ValueType  # 3
    ASSOCIATION_RELATION_SIBLING: _AssociationRelation.ValueType  # 4

class AssociationRelation(_AssociationRelation, metaclass=_AssociationRelationEnumTypeWrapper): ...

ASSOCIATION_RELATION_UNSPECIFIED: AssociationRelation.ValueType  # 0
"""Unset enum"""
ASSOCIATION_RELATION_NO_RELATION: AssociationRelation.ValueType  # 1
ASSOCIATION_RELATION_PARENT: AssociationRelation.ValueType  # 2
ASSOCIATION_RELATION_CHILD: AssociationRelation.ValueType  # 3
ASSOCIATION_RELATION_SIBLING: AssociationRelation.ValueType  # 4
Global___AssociationRelation: _TypeAlias = AssociationRelation  # noqa: Y015

@_typing.final
class AssociatedDetection(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    NODE_ID_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    ASSOCIATION_TYPE_FIELD_NUMBER: _builtins.int
    node_id: _builtins.str
    """ULID for the node where the assoicated detection has originiated"""
    object_id: _builtins.str
    """ULID for the object detected in the environment"""
    association_type: Global___AssociationRelation.ValueType
    """Relationship of associated detection to this message"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp the message was sent"""

    def __init__(
        self,
        *,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        node_id: _builtins.str | None = ...,
        object_id: _builtins.str | None = ...,
        association_type: Global___AssociationRelation.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_association_type", b"_association_type", "_node_id", b"_node_id", "_object_id", b"_object_id", "_timestamp", b"_timestamp", "association_type", b"association_type", "node_id", b"node_id", "object_id", b"object_id", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_association_type", b"_association_type", "_node_id", b"_node_id", "_object_id", b"_object_id", "_timestamp", b"_timestamp", "association_type", b"association_type", "node_id", b"node_id", "object_id", b"object_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__association_type: _TypeAlias = _typing.Literal["association_type"]  # noqa: Y015
    _WhichOneofArgType__association_type: _TypeAlias = _typing.Literal["_association_type", b"_association_type"]  # noqa: Y015
    _WhichOneofReturnType__node_id: _TypeAlias = _typing.Literal["node_id"]  # noqa: Y015
    _WhichOneofArgType__node_id: _TypeAlias = _typing.Literal["_node_id", b"_node_id"]  # noqa: Y015
    _WhichOneofReturnType__object_id: _TypeAlias = _typing.Literal["object_id"]  # noqa: Y015
    _WhichOneofArgType__object_id: _TypeAlias = _typing.Literal["_object_id", b"_object_id"]  # noqa: Y015
    _WhichOneofReturnType__timestamp: _TypeAlias = _typing.Literal["timestamp"]  # noqa: Y015
    _WhichOneofArgType__timestamp: _TypeAlias = _typing.Literal["_timestamp", b"_timestamp"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__association_type) -> _WhichOneofReturnType__association_type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__node_id) -> _WhichOneofReturnType__node_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__object_id) -> _WhichOneofReturnType__object_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timestamp) -> _WhichOneofReturnType__timestamp | None: ...

Global___AssociatedDetection: _TypeAlias = AssociatedDetection  # noqa: Y015
