"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AssociatedFile(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    """Type of file contained available at the URL"""
    url: _builtins.str
    """The network address of where the file can be accessed"""
    def __init__(
        self,
        *,
        type: _builtins.str | None = ...,
        url: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_type", b"_type", "_url", b"_url", "type", b"type", "url", b"url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_type", b"_type", "_url", b"_url", "type", b"type", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
    _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
    _WhichOneofReturnType__url: _TypeAlias = _typing.Literal["url"]  # noqa: Y015
    _WhichOneofArgType__url: _TypeAlias = _typing.Literal["_url", b"_url"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__url) -> _WhichOneofReturnType__url | None: ...

Global___AssociatedFile: _TypeAlias = AssociatedFile  # noqa: Y015
