"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from sapient_msg.bsi_flex_335_v2_0 import associated_detection_pb2 as _associated_detection_pb2
from sapient_msg.bsi_flex_335_v2_0 import associated_file_pb2 as _associated_file_pb2
from sapient_msg.bsi_flex_335_v2_0 import location_pb2 as _location_pb2
from sapient_msg.bsi_flex_335_v2_0 import range_bearing_pb2 as _range_bearing_pb2
from sapient_msg.bsi_flex_335_v2_0 import velocity_pb2 as _velocity_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DetectionReport(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PredictedLocation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RANGE_BEARING_FIELD_NUMBER: _builtins.int
        LOCATION_FIELD_NUMBER: _builtins.int
        PREDICTED_TIMESTAMP_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def range_bearing(self) -> _range_bearing_pb2.RangeBearing:
            """Predicted location of object being detected using an range-bearing coordinate system"""

        @_builtins.property
        def location(self) -> _location_pb2.Location:
            """Predicted location of object being detected using an 'x-y-z' coordinate system"""

        @_builtins.property
        def predicted_timestamp(self) -> _timestamp_pb2.Timestamp:
            """The timestamp of when the detected object will be at the predicted location"""

        def __init__(
            self,
            *,
            range_bearing: _range_bearing_pb2.RangeBearing | None = ...,
            location: _location_pb2.Location | None = ...,
            predicted_timestamp: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_predicted_timestamp", b"_predicted_timestamp", "location", b"location", "predicted_location_oneof", b"predicted_location_oneof", "predicted_timestamp", b"predicted_timestamp", "range_bearing", b"range_bearing"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_predicted_timestamp", b"_predicted_timestamp", "location", b"location", "predicted_location_oneof", b"predicted_location_oneof", "predicted_timestamp", b"predicted_timestamp", "range_bearing", b"range_bearing"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__predicted_timestamp: _TypeAlias = _typing.Literal["predicted_timestamp"]  # noqa: Y015
        _WhichOneofArgType__predicted_timestamp: _TypeAlias = _typing.Literal["_predicted_timestamp", b"_predicted_timestamp"]  # noqa: Y015
        _WhichOneofReturnType_predicted_location_oneof: _TypeAlias = _typing.Literal["range_bearing", "location"]  # noqa: Y015
        _WhichOneofArgType_predicted_location_oneof: _TypeAlias = _typing.Literal["predicted_location_oneof", b"predicted_location_oneof"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__predicted_timestamp) -> _WhichOneofReturnType__predicted_timestamp | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_predicted_location_oneof) -> _WhichOneofReturnType_predicted_location_oneof | None: ...

    @_typing.final
    class TrackObjectInfo(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        ERROR_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """The type of object_info being reported (e.g. colour)"""
        value: _builtins.str
        """The value of the object_info being reported (e.g. red)"""
        error: _builtins.float
        """Any error associated with the object_info"""
        def __init__(
            self,
            *,
            type: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
            error: _builtins.float | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_error", b"_error", "_type", b"_type", "_value", b"_value", "error", b"error", "type", b"type", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_error", b"_error", "_type", b"_type", "_value", b"_value", "error", b"error", "type", b"type", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__error: _TypeAlias = _typing.Literal["error"]  # noqa: Y015
        _WhichOneofArgType__error: _TypeAlias = _typing.Literal["_error", b"_error"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        _WhichOneofReturnType__value: _TypeAlias = _typing.Literal["value"]  # noqa: Y015
        _WhichOneofArgType__value: _TypeAlias = _typing.Literal["_value", b"_value"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__error) -> _WhichOneofReturnType__error | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__value) -> _WhichOneofReturnType__value | None: ...

    @_typing.final
    class DetectionReportClassification(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        CONFIDENCE_FIELD_NUMBER: _builtins.int
        SUB_CLASS_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """Classification of the detected object being reported"""
        confidence: _builtins.float
        """Confidence (0-1) that this is the correct classification of the detected object"""
        @_builtins.property
        def sub_class(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.SubClass]:
            """Any sub-classifications of the detected object"""

        def __init__(
            self,
            *,
            type: _builtins.str | None = ...,
            confidence: _builtins.float | None = ...,
            sub_class: _abc.Iterable[Global___DetectionReport.SubClass] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_confidence", b"_confidence", "_type", b"_type", "confidence", b"confidence", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_confidence", b"_confidence", "_type", b"_type", "confidence", b"confidence", "sub_class", b"sub_class", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__confidence: _TypeAlias = _typing.Literal["confidence"]  # noqa: Y015
        _WhichOneofArgType__confidence: _TypeAlias = _typing.Literal["_confidence", b"_confidence"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__confidence) -> _WhichOneofReturnType__confidence | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class SubClass(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        CONFIDENCE_FIELD_NUMBER: _builtins.int
        LEVEL_FIELD_NUMBER: _builtins.int
        SUB_CLASS_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """Classification of the detected object being reported"""
        confidence: _builtins.float
        """Confidence (0-1) that this is the correct classification of the detected object"""
        level: _builtins.int
        """The level of sub-classification (top level is 0, the first sub-class is 1, etc.)"""
        @_builtins.property
        def sub_class(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.SubClass]:
            """Any sub-classifications of the detected object"""

        def __init__(
            self,
            *,
            type: _builtins.str | None = ...,
            confidence: _builtins.float | None = ...,
            level: _builtins.int | None = ...,
            sub_class: _abc.Iterable[Global___DetectionReport.SubClass] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_confidence", b"_confidence", "_level", b"_level", "_type", b"_type", "confidence", b"confidence", "level", b"level", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_confidence", b"_confidence", "_level", b"_level", "_type", b"_type", "confidence", b"confidence", "level", b"level", "sub_class", b"sub_class", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__confidence: _TypeAlias = _typing.Literal["confidence"]  # noqa: Y015
        _WhichOneofArgType__confidence: _TypeAlias = _typing.Literal["_confidence", b"_confidence"]  # noqa: Y015
        _WhichOneofReturnType__level: _TypeAlias = _typing.Literal["level"]  # noqa: Y015
        _WhichOneofArgType__level: _TypeAlias = _typing.Literal["_level", b"_level"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__confidence) -> _WhichOneofReturnType__confidence | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__level) -> _WhichOneofReturnType__level | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class Behaviour(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        CONFIDENCE_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """Behviouar of the detected object being reported"""
        confidence: _builtins.float
        """Confidence (0-1) that this is the correct behvaiour of the detected object"""
        def __init__(
            self,
            *,
            type: _builtins.str | None = ...,
            confidence: _builtins.float | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_confidence", b"_confidence", "_type", b"_type", "confidence", b"confidence", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_confidence", b"_confidence", "_type", b"_type", "confidence", b"confidence", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__confidence: _TypeAlias = _typing.Literal["confidence"]  # noqa: Y015
        _WhichOneofArgType__confidence: _TypeAlias = _typing.Literal["_confidence", b"_confidence"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__confidence) -> _WhichOneofReturnType__confidence | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class Signal(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        AMPLITUDE_FIELD_NUMBER: _builtins.int
        START_FREQUENCY_FIELD_NUMBER: _builtins.int
        CENTRE_FREQUENCY_FIELD_NUMBER: _builtins.int
        STOP_FREQUENCY_FIELD_NUMBER: _builtins.int
        PULSE_DURATION_FIELD_NUMBER: _builtins.int
        amplitude: _builtins.float
        """Peak amplitude of the signal being reported"""
        start_frequency: _builtins.float
        """Lowest frequency of the band being reported"""
        centre_frequency: _builtins.float
        """Centre frequency of the band being reported"""
        stop_frequency: _builtins.float
        """Highest frequency of the band being reported"""
        pulse_duration: _builtins.float
        """Pulse duration of the signal being reported"""
        def __init__(
            self,
            *,
            amplitude: _builtins.float | None = ...,
            start_frequency: _builtins.float | None = ...,
            centre_frequency: _builtins.float | None = ...,
            stop_frequency: _builtins.float | None = ...,
            pulse_duration: _builtins.float | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_amplitude", b"_amplitude", "_centre_frequency", b"_centre_frequency", "_pulse_duration", b"_pulse_duration", "_start_frequency", b"_start_frequency", "_stop_frequency", b"_stop_frequency", "amplitude", b"amplitude", "centre_frequency", b"centre_frequency", "pulse_duration", b"pulse_duration", "start_frequency", b"start_frequency", "stop_frequency", b"stop_frequency"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_amplitude", b"_amplitude", "_centre_frequency", b"_centre_frequency", "_pulse_duration", b"_pulse_duration", "_start_frequency", b"_start_frequency", "_stop_frequency", b"_stop_frequency", "amplitude", b"amplitude", "centre_frequency", b"centre_frequency", "pulse_duration", b"pulse_duration", "start_frequency", b"start_frequency", "stop_frequency", b"stop_frequency"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__amplitude: _TypeAlias = _typing.Literal["amplitude"]  # noqa: Y015
        _WhichOneofArgType__amplitude: _TypeAlias = _typing.Literal["_amplitude", b"_amplitude"]  # noqa: Y015
        _WhichOneofReturnType__centre_frequency: _TypeAlias = _typing.Literal["centre_frequency"]  # noqa: Y015
        _WhichOneofArgType__centre_frequency: _TypeAlias = _typing.Literal["_centre_frequency", b"_centre_frequency"]  # noqa: Y015
        _WhichOneofReturnType__pulse_duration: _TypeAlias = _typing.Literal["pulse_duration"]  # noqa: Y015
        _WhichOneofArgType__pulse_duration: _TypeAlias = _typing.Literal["_pulse_duration", b"_pulse_duration"]  # noqa: Y015
        _WhichOneofReturnType__start_frequency: _TypeAlias = _typing.Literal["start_frequency"]  # noqa: Y015
        _WhichOneofArgType__start_frequency: _TypeAlias = _typing.Literal["_start_frequency", b"_start_frequency"]  # noqa: Y015
        _WhichOneofReturnType__stop_frequency: _TypeAlias = _typing.Literal["stop_frequency"]  # noqa: Y015
        _WhichOneofArgType__stop_frequency: _TypeAlias = _typing.Literal["_stop_frequency", b"_stop_frequency"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__amplitude) -> _WhichOneofReturnType__amplitude | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__centre_frequency) -> _WhichOneofReturnType__centre_frequency | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__pulse_duration) -> _WhichOneofReturnType__pulse_duration | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__start_frequency) -> _WhichOneofReturnType__start_frequency | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__stop_frequency) -> _WhichOneofReturnType__stop_frequency | None: ...

    @_typing.final
    class DerivedDetection(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        NODE_ID_FIELD_NUMBER: _builtins.int
        OBJECT_ID_FIELD_NUMBER: _builtins.int
        node_id: _builtins.str
        """UUID for the node where the assoicated detection has originiated"""
        object_id: _builtins.str
        """ULID for the object detected in the environment"""
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """UTC timestamp the message was sent"""

        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            node_id: _builtins.str | None = ...,
            object_id: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_node_id", b"_node_id", "_object_id", b"_object_id", "_timestamp", b"_timestamp", "node_id", b"node_id", "object_id", b"object_id", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_node_id", b"_node_id", "_object_id", b"_object_id", "_timestamp", b"_timestamp", "node_id", b"node_id", "object_id", b"object_id", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__node_id: _TypeAlias = _typing.Literal["node_id"]  # noqa: Y015
        _WhichOneofArgType__node_id: _TypeAlias = _typing.Literal["_node_id", b"_node_id"]  # noqa: Y015
        _WhichOneofReturnType__object_id: _TypeAlias = _typing.Literal["object_id"]  # noqa: Y015
        _WhichOneofArgType__object_id: _TypeAlias = _typing.Literal["_object_id", b"_object_id"]  # noqa: Y015
        _WhichOneofReturnType__timestamp: _TypeAlias = _typing.Literal["timestamp"]  # noqa: Y015
        _WhichOneofArgType__timestamp: _TypeAlias = _typing.Literal["_timestamp", b"_timestamp"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__node_id) -> _WhichOneofReturnType__node_id | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__object_id) -> _WhichOneofReturnType__object_id | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__timestamp) -> _WhichOneofReturnType__timestamp | None: ...

    REPORT_ID_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    TASK_ID_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    RANGE_BEARING_FIELD_NUMBER: _builtins.int
    LOCATION_FIELD_NUMBER: _builtins.int
    DETECTION_CONFIDENCE_FIELD_NUMBER: _builtins.int
    TRACK_INFO_FIELD_NUMBER: _builtins.int
    PREDICTION_LOCATION_FIELD_NUMBER: _builtins.int
    OBJECT_INFO_FIELD_NUMBER: _builtins.int
    CLASSIFICATION_FIELD_NUMBER: _builtins.int
    BEHAVIOUR_FIELD_NUMBER: _builtins.int
    ASSOCIATED_FILE_FIELD_NUMBER: _builtins.int
    SIGNAL_FIELD_NUMBER: _builtins.int
    ASSOCIATED_DETECTION_FIELD_NUMBER: _builtins.int
    DERIVED_DETECTION_FIELD_NUMBER: _builtins.int
    ENU_VELOCITY_FIELD_NUMBER: _builtins.int
    COLOUR_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    report_id: _builtins.str
    """ULID for the message"""
    object_id: _builtins.str
    """ULID for the object detected in the environment"""
    task_id: _builtins.str
    """ULID of the task the ASM is currently performing"""
    state: _builtins.str
    """Whether a special case is in effect (e.g. object lost)"""
    detection_confidence: _builtins.float
    """The confidence that the detection is present as a percentage (0-1)"""
    colour: _builtins.str
    """Colour of the object being reported"""
    id: _builtins.str
    """ID of the object being reported (e.g. the tail number of aircraft)"""
    @_builtins.property
    def range_bearing(self) -> _range_bearing_pb2.RangeBearing:
        """Location of object being detected using an range-bearing coordinate system"""

    @_builtins.property
    def location(self) -> _location_pb2.Location:
        """Location of object being detected using an 'x-y-z' coordinate system"""

    @_builtins.property
    def track_info(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.TrackObjectInfo]:
        """Additional information about the track as defined in the ASM's registration message"""

    @_builtins.property
    def prediction_location(self) -> Global___DetectionReport.PredictedLocation:
        """Location where the object is predicted to be at a future time"""

    @_builtins.property
    def object_info(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.TrackObjectInfo]:
        """Additional information about the detected object as defined in the ASM's registration message"""

    @_builtins.property
    def classification(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.DetectionReportClassification]:
        """Classification information about the detected object"""

    @_builtins.property
    def behaviour(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.Behaviour]:
        """Behavioural information about the detected object"""

    @_builtins.property
    def associated_file(self) -> _containers.RepeatedCompositeFieldContainer[_associated_file_pb2.AssociatedFile]:
        """URLs to any additional files relating to the object which hosted on the network"""

    @_builtins.property
    def signal(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.Signal]:
        """RF signal information about the detected object"""

    @_builtins.property
    def associated_detection(self) -> _containers.RepeatedCompositeFieldContainer[_associated_detection_pb2.AssociatedDetection]:
        """Other SAPIENT detections associated with this detection"""

    @_builtins.property
    def derived_detection(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionReport.DerivedDetection]:
        """Other SAPIENT detections dervied from this detection"""

    @_builtins.property
    def enu_velocity(self) -> _velocity_pb2.ENUVelocity:
        """       RYPVelocity ryp_velocity = 17; // Velocity of object relative to sensor location and sensor pointing direction  
               GHCVelocity ghc_velocity = 18; // Velocity of object in global coordinates in the style of Air Traffic Management
        Velocity of object as a vector in global cartesian coordinates
        """

    def __init__(
        self,
        *,
        report_id: _builtins.str | None = ...,
        object_id: _builtins.str | None = ...,
        task_id: _builtins.str | None = ...,
        state: _builtins.str | None = ...,
        range_bearing: _range_bearing_pb2.RangeBearing | None = ...,
        location: _location_pb2.Location | None = ...,
        detection_confidence: _builtins.float | None = ...,
        track_info: _abc.Iterable[Global___DetectionReport.TrackObjectInfo] | None = ...,
        prediction_location: Global___DetectionReport.PredictedLocation | None = ...,
        object_info: _abc.Iterable[Global___DetectionReport.TrackObjectInfo] | None = ...,
        classification: _abc.Iterable[Global___DetectionReport.DetectionReportClassification] | None = ...,
        behaviour: _abc.Iterable[Global___DetectionReport.Behaviour] | None = ...,
        associated_file: _abc.Iterable[_associated_file_pb2.AssociatedFile] | None = ...,
        signal: _abc.Iterable[Global___DetectionReport.Signal] | None = ...,
        associated_detection: _abc.Iterable[_associated_detection_pb2.AssociatedDetection] | None = ...,
        derived_detection: _abc.Iterable[Global___DetectionReport.DerivedDetection] | None = ...,
        enu_velocity: _velocity_pb2.ENUVelocity | None = ...,
        colour: _builtins.str | None = ...,
        id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_colour", b"_colour", "_detection_confidence", b"_detection_confidence", "_id", b"_id", "_object_id", b"_object_id", "_prediction_location", b"_prediction_location", "_report_id", b"_report_id", "_state", b"_state", "_task_id", b"_task_id", "colour", b"colour", "detection_confidence", b"detection_confidence", "enu_velocity", b"enu_velocity", "id", b"id", "location", b"location", "location_oneof", b"location_oneof", "object_id", b"object_id", "prediction_location", b"prediction_location", "range_bearing", b"range_bearing", "report_id", b"report_id", "state", b"state", "task_id", b"task_id", "velocity_oneof", b"velocity_oneof"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_colour", b"_colour", "_detection_confidence", b"_detection_confidence", "_id", b"_id", "_object_id", b"_object_id", "_prediction_location", b"_prediction_location", "_report_id", b"_report_id", "_state", b"_state", "_task_id", b"_task_id", "associated_detection", b"associated_detection", "associated_file", b"associated_file", "behaviour", b"behaviour", "classification", b"classification", "colour", b"colour", "derived_detection", b"derived_detection", "detection_confidence", b"detection_confidence", "enu_velocity", b"enu_velocity", "id", b"id", "location", b"location", "location_oneof", b"location_oneof", "object_id", b"object_id", "object_info", b"object_info", "prediction_location", b"prediction_location", "range_bearing", b"range_bearing", "report_id", b"report_id", "signal", b"signal", "state", b"state", "task_id", b"task_id", "track_info", b"track_info", "velocity_oneof", b"velocity_oneof"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__colour: _TypeAlias = _typing.Literal["colour"]  # noqa: Y015
    _WhichOneofArgType__colour: _TypeAlias = _typing.Literal["_colour", b"_colour"]  # noqa: Y015
    _WhichOneofReturnType__detection_confidence: _TypeAlias = _typing.Literal["detection_confidence"]  # noqa: Y015
    _WhichOneofArgType__detection_confidence: _TypeAlias = _typing.Literal["_detection_confidence", b"_detection_confidence"]  # noqa: Y015
    _WhichOneofReturnType__id: _TypeAlias = _typing.Literal["id"]  # noqa: Y015
    _WhichOneofArgType__id: _TypeAlias = _typing.Literal["_id", b"_id"]  # noqa: Y015
    _WhichOneofReturnType__object_id: _TypeAlias = _typing.Literal["object_id"]  # noqa: Y015
    _WhichOneofArgType__object_id: _TypeAlias = _typing.Literal["_object_id", b"_object_id"]  # noqa: Y015
    _WhichOneofReturnType__prediction_location: _TypeAlias = _typing.Literal["prediction_location"]  # noqa: Y015
    _WhichOneofArgType__prediction_location: _TypeAlias = _typing.Literal["_prediction_location", b"_prediction_location"]  # noqa: Y015
    _WhichOneofReturnType__report_id: _TypeAlias = _typing.Literal["report_id"]  # noqa: Y015
    _WhichOneofArgType__report_id: _TypeAlias = _typing.Literal["_report_id", b"_report_id"]  # noqa: Y015
    _WhichOneofReturnType__state: _TypeAlias = _typing.Literal["state"]  # noqa: Y015
    _WhichOneofArgType__state: _TypeAlias = _typing.Literal["_state", b"_state"]  # noqa: Y015
    _WhichOneofReturnType__task_id: _TypeAlias = _typing.Literal["task_id"]  # noqa: Y015
    _WhichOneofArgType__task_id: _TypeAlias = _typing.Literal["_task_id", b"_task_id"]  # noqa: Y015
    _WhichOneofReturnType_location_oneof: _TypeAlias = _typing.Literal["range_bearing", "location"]  # noqa: Y015
    _WhichOneofArgType_location_oneof: _TypeAlias = _typing.Literal["location_oneof", b"location_oneof"]  # noqa: Y015
    _WhichOneofReturnType_velocity_oneof: _TypeAlias = _typing.Literal["enu_velocity"]  # noqa: Y015
    _WhichOneofArgType_velocity_oneof: _TypeAlias = _typing.Literal["velocity_oneof", b"velocity_oneof"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__colour) -> _WhichOneofReturnType__colour | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__detection_confidence) -> _WhichOneofReturnType__detection_confidence | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__id) -> _WhichOneofReturnType__id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__object_id) -> _WhichOneofReturnType__object_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__prediction_location) -> _WhichOneofReturnType__prediction_location | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__report_id) -> _WhichOneofReturnType__report_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__state) -> _WhichOneofReturnType__state | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_id) -> _WhichOneofReturnType__task_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_location_oneof) -> _WhichOneofReturnType_location_oneof | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_velocity_oneof) -> _WhichOneofReturnType_velocity_oneof | None: ...

Global___DetectionReport: _TypeAlias = DetectionReport  # noqa: Y015
