"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Error(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    PACKET_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    packet: _builtins.bytes
    """Packet which caused the error"""
    @_builtins.property
    def error_message(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """   optional string error_message = 2 [(field_options) = {is_mandatory: true}]; // Description of the error being reported
        Description of the error being reported, this field is an array to allow multiple errors to be reported in one go
        """

    def __init__(
        self,
        *,
        packet: _builtins.bytes | None = ...,
        error_message: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_packet", b"_packet", "packet", b"packet"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_packet", b"_packet", "error_message", b"error_message", "packet", b"packet"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__packet: _TypeAlias = _typing.Literal["packet"]  # noqa: Y015
    _WhichOneofArgType__packet: _TypeAlias = _typing.Literal["_packet", b"_packet"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__packet) -> _WhichOneofReturnType__packet | None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015
