"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FollowObject(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    FOLLOW_OBJECT_ID_FIELD_NUMBER: _builtins.int
    follow_object_id: _builtins.str
    """This field specifies the object_id (from the Detection Messages) of the object the mobile node should follow"""
    def __init__(
        self,
        *,
        follow_object_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["follow_object_id", b"follow_object_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FollowObject: _TypeAlias = FollowObject  # noqa: Y015
