"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _LocationCoordinateSystem:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LocationCoordinateSystemEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LocationCoordinateSystem.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOCATION_COORDINATE_SYSTEM_UNSPECIFIED: _LocationCoordinateSystem.ValueType  # 0
    """Co-ordinate system/units not defined"""
    LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M: _LocationCoordinateSystem.ValueType  # 1
    """Latitude/Longitude in decimal-degrees/metres"""
    LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M: _LocationCoordinateSystem.ValueType  # 2
    """Latitude/Longitude in radians/metres"""
    LOCATION_COORDINATE_SYSTEM_UTM_M: _LocationCoordinateSystem.ValueType  # 5
    """   LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_F = 3; // Latitude/Longitude in decimal-degrees/feet - DEPRECATED
       LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_F = 4; // Latitude/Longitude in radians/feet - DEPRECATED
    UTM with altitude in metres
    """

class LocationCoordinateSystem(_LocationCoordinateSystem, metaclass=_LocationCoordinateSystemEnumTypeWrapper): ...

LOCATION_COORDINATE_SYSTEM_UNSPECIFIED: LocationCoordinateSystem.ValueType  # 0
"""Co-ordinate system/units not defined"""
LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M: LocationCoordinateSystem.ValueType  # 1
"""Latitude/Longitude in decimal-degrees/metres"""
LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M: LocationCoordinateSystem.ValueType  # 2
"""Latitude/Longitude in radians/metres"""
LOCATION_COORDINATE_SYSTEM_UTM_M: LocationCoordinateSystem.ValueType  # 5
"""   LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_F = 3; // Latitude/Longitude in decimal-degrees/feet - DEPRECATED
   LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_F = 4; // Latitude/Longitude in radians/feet - DEPRECATED
UTM with altitude in metres
"""
Global___LocationCoordinateSystem: _TypeAlias = LocationCoordinateSystem  # noqa: Y015

class _LocationDatum:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LocationDatumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LocationDatum.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOCATION_DATUM_UNSPECIFIED: _LocationDatum.ValueType  # 0
    """Datum not defined"""
    LOCATION_DATUM_WGS84_E: _LocationDatum.ValueType  # 1
    """WGS84 Ellipsoid"""
    LOCATION_DATUM_WGS84_G: _LocationDatum.ValueType  # 2
    """WGS84 Geoid"""

class LocationDatum(_LocationDatum, metaclass=_LocationDatumEnumTypeWrapper): ...

LOCATION_DATUM_UNSPECIFIED: LocationDatum.ValueType  # 0
"""Datum not defined"""
LOCATION_DATUM_WGS84_E: LocationDatum.ValueType  # 1
"""WGS84 Ellipsoid"""
LOCATION_DATUM_WGS84_G: LocationDatum.ValueType  # 2
"""WGS84 Geoid"""
Global___LocationDatum: _TypeAlias = LocationDatum  # noqa: Y015

@_typing.final
class LocationList(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    LOCATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def locations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Location]:
        """List of locations used to define a region"""

    def __init__(
        self,
        *,
        locations: _abc.Iterable[Global___Location] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["locations", b"locations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LocationList: _TypeAlias = LocationList  # noqa: Y015

@_typing.final
class Location(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    Z_FIELD_NUMBER: _builtins.int
    X_ERROR_FIELD_NUMBER: _builtins.int
    Y_ERROR_FIELD_NUMBER: _builtins.int
    Z_ERROR_FIELD_NUMBER: _builtins.int
    COORDINATE_SYSTEM_FIELD_NUMBER: _builtins.int
    DATUM_FIELD_NUMBER: _builtins.int
    UTM_ZONE_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    """X-coordinate (normally longitude)"""
    y: _builtins.float
    """Y-coordinate (normally latitude)"""
    z: _builtins.float
    """Z-coordinate (normally altitude)"""
    x_error: _builtins.float
    """X-coordinate error"""
    y_error: _builtins.float
    """Y-coordinate error"""
    z_error: _builtins.float
    """Z-coordinate error"""
    coordinate_system: Global___LocationCoordinateSystem.ValueType
    """Coordinate system used"""
    datum: Global___LocationDatum.ValueType
    """Datum used"""
    utm_zone: _builtins.str
    """For reporting locations in an adjacent UTM zone"""
    def __init__(
        self,
        *,
        x: _builtins.float | None = ...,
        y: _builtins.float | None = ...,
        z: _builtins.float | None = ...,
        x_error: _builtins.float | None = ...,
        y_error: _builtins.float | None = ...,
        z_error: _builtins.float | None = ...,
        coordinate_system: Global___LocationCoordinateSystem.ValueType | None = ...,
        datum: Global___LocationDatum.ValueType | None = ...,
        utm_zone: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_coordinate_system", b"_coordinate_system", "_datum", b"_datum", "_utm_zone", b"_utm_zone", "_x", b"_x", "_x_error", b"_x_error", "_y", b"_y", "_y_error", b"_y_error", "_z", b"_z", "_z_error", b"_z_error", "coordinate_system", b"coordinate_system", "datum", b"datum", "utm_zone", b"utm_zone", "x", b"x", "x_error", b"x_error", "y", b"y", "y_error", b"y_error", "z", b"z", "z_error", b"z_error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_coordinate_system", b"_coordinate_system", "_datum", b"_datum", "_utm_zone", b"_utm_zone", "_x", b"_x", "_x_error", b"_x_error", "_y", b"_y", "_y_error", b"_y_error", "_z", b"_z", "_z_error", b"_z_error", "coordinate_system", b"coordinate_system", "datum", b"datum", "utm_zone", b"utm_zone", "x", b"x", "x_error", b"x_error", "y", b"y", "y_error", b"y_error", "z", b"z", "z_error", b"z_error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__coordinate_system: _TypeAlias = _typing.Literal["coordinate_system"]  # noqa: Y015
    _WhichOneofArgType__coordinate_system: _TypeAlias = _typing.Literal["_coordinate_system", b"_coordinate_system"]  # noqa: Y015
    _WhichOneofReturnType__datum: _TypeAlias = _typing.Literal["datum"]  # noqa: Y015
    _WhichOneofArgType__datum: _TypeAlias = _typing.Literal["_datum", b"_datum"]  # noqa: Y015
    _WhichOneofReturnType__utm_zone: _TypeAlias = _typing.Literal["utm_zone"]  # noqa: Y015
    _WhichOneofArgType__utm_zone: _TypeAlias = _typing.Literal["_utm_zone", b"_utm_zone"]  # noqa: Y015
    _WhichOneofReturnType__x: _TypeAlias = _typing.Literal["x"]  # noqa: Y015
    _WhichOneofArgType__x: _TypeAlias = _typing.Literal["_x", b"_x"]  # noqa: Y015
    _WhichOneofReturnType__x_error: _TypeAlias = _typing.Literal["x_error"]  # noqa: Y015
    _WhichOneofArgType__x_error: _TypeAlias = _typing.Literal["_x_error", b"_x_error"]  # noqa: Y015
    _WhichOneofReturnType__y: _TypeAlias = _typing.Literal["y"]  # noqa: Y015
    _WhichOneofArgType__y: _TypeAlias = _typing.Literal["_y", b"_y"]  # noqa: Y015
    _WhichOneofReturnType__y_error: _TypeAlias = _typing.Literal["y_error"]  # noqa: Y015
    _WhichOneofArgType__y_error: _TypeAlias = _typing.Literal["_y_error", b"_y_error"]  # noqa: Y015
    _WhichOneofReturnType__z: _TypeAlias = _typing.Literal["z"]  # noqa: Y015
    _WhichOneofArgType__z: _TypeAlias = _typing.Literal["_z", b"_z"]  # noqa: Y015
    _WhichOneofReturnType__z_error: _TypeAlias = _typing.Literal["z_error"]  # noqa: Y015
    _WhichOneofArgType__z_error: _TypeAlias = _typing.Literal["_z_error", b"_z_error"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__coordinate_system) -> _WhichOneofReturnType__coordinate_system | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__datum) -> _WhichOneofReturnType__datum | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__utm_zone) -> _WhichOneofReturnType__utm_zone | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__x) -> _WhichOneofReturnType__x | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__x_error) -> _WhichOneofReturnType__x_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__y) -> _WhichOneofReturnType__y | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__y_error) -> _WhichOneofReturnType__y_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__z) -> _WhichOneofReturnType__z | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__z_error) -> _WhichOneofReturnType__z_error | None: ...

Global___Location: _TypeAlias = Location  # noqa: Y015
