"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sapient_msg.bsi_flex_335_v2_0 import location_pb2 as _location_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _RangeBearingCoordinateSystem:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RangeBearingCoordinateSystemEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RangeBearingCoordinateSystem.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED: _RangeBearingCoordinateSystem.ValueType  # 0
    """Co-ordinate system/units not defined"""
    RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_M: _RangeBearingCoordinateSystem.ValueType  # 1
    """Values in decimal-degrees and meters"""
    RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_M: _RangeBearingCoordinateSystem.ValueType  # 2
    """Values in radians and meters"""
    RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_KM: _RangeBearingCoordinateSystem.ValueType  # 3
    """Values in decimal-degrees and kilometers"""
    RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_KM: _RangeBearingCoordinateSystem.ValueType  # 4
    """Values in radians and kilometers"""

class RangeBearingCoordinateSystem(_RangeBearingCoordinateSystem, metaclass=_RangeBearingCoordinateSystemEnumTypeWrapper): ...

RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED: RangeBearingCoordinateSystem.ValueType  # 0
"""Co-ordinate system/units not defined"""
RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_M: RangeBearingCoordinateSystem.ValueType  # 1
"""Values in decimal-degrees and meters"""
RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_M: RangeBearingCoordinateSystem.ValueType  # 2
"""Values in radians and meters"""
RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_KM: RangeBearingCoordinateSystem.ValueType  # 3
"""Values in decimal-degrees and kilometers"""
RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_KM: RangeBearingCoordinateSystem.ValueType  # 4
"""Values in radians and kilometers"""
Global___RangeBearingCoordinateSystem: _TypeAlias = RangeBearingCoordinateSystem  # noqa: Y015

class _RangeBearingDatum:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RangeBearingDatumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RangeBearingDatum.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RANGE_BEARING_DATUM_UNSPECIFIED: _RangeBearingDatum.ValueType  # 0
    """Datum not defined"""
    RANGE_BEARING_DATUM_TRUE: _RangeBearingDatum.ValueType  # 1
    """True North"""
    RANGE_BEARING_DATUM_MAGNETIC: _RangeBearingDatum.ValueType  # 2
    """Magnetic North"""
    RANGE_BEARING_DATUM_GRID: _RangeBearingDatum.ValueType  # 3
    """Grid North"""
    RANGE_BEARING_DATUM_PLATFORM: _RangeBearingDatum.ValueType  # 4
    """'North' is the heading of the platform carrying the node"""

class RangeBearingDatum(_RangeBearingDatum, metaclass=_RangeBearingDatumEnumTypeWrapper): ...

RANGE_BEARING_DATUM_UNSPECIFIED: RangeBearingDatum.ValueType  # 0
"""Datum not defined"""
RANGE_BEARING_DATUM_TRUE: RangeBearingDatum.ValueType  # 1
"""True North"""
RANGE_BEARING_DATUM_MAGNETIC: RangeBearingDatum.ValueType  # 2
"""Magnetic North"""
RANGE_BEARING_DATUM_GRID: RangeBearingDatum.ValueType  # 3
"""Grid North"""
RANGE_BEARING_DATUM_PLATFORM: RangeBearingDatum.ValueType  # 4
"""'North' is the heading of the platform carrying the node"""
Global___RangeBearingDatum: _TypeAlias = RangeBearingDatum  # noqa: Y015

@_typing.final
class RangeBearing(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    ELEVATION_FIELD_NUMBER: _builtins.int
    AZIMUTH_FIELD_NUMBER: _builtins.int
    RANGE_FIELD_NUMBER: _builtins.int
    ELEVATION_ERROR_FIELD_NUMBER: _builtins.int
    AZIMUTH_ERROR_FIELD_NUMBER: _builtins.int
    RANGE_ERROR_FIELD_NUMBER: _builtins.int
    COORDINATE_SYSTEM_FIELD_NUMBER: _builtins.int
    DATUM_FIELD_NUMBER: _builtins.int
    elevation: _builtins.float
    """Elevation in relation to node's horizon"""
    azimuth: _builtins.float
    """Azimuth in relation to the node's north"""
    range: _builtins.float
    """Range from the node's location"""
    elevation_error: _builtins.float
    """Elevation error"""
    azimuth_error: _builtins.float
    """Azimuth error"""
    range_error: _builtins.float
    """Range Error"""
    coordinate_system: Global___RangeBearingCoordinateSystem.ValueType
    """Units used by the range bearing"""
    datum: Global___RangeBearingDatum.ValueType
    """Datum or 'north' used by the range bearing"""
    def __init__(
        self,
        *,
        elevation: _builtins.float | None = ...,
        azimuth: _builtins.float | None = ...,
        range: _builtins.float | None = ...,
        elevation_error: _builtins.float | None = ...,
        azimuth_error: _builtins.float | None = ...,
        range_error: _builtins.float | None = ...,
        coordinate_system: Global___RangeBearingCoordinateSystem.ValueType | None = ...,
        datum: Global___RangeBearingDatum.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_azimuth", b"_azimuth", "_azimuth_error", b"_azimuth_error", "_coordinate_system", b"_coordinate_system", "_datum", b"_datum", "_elevation", b"_elevation", "_elevation_error", b"_elevation_error", "_range", b"_range", "_range_error", b"_range_error", "azimuth", b"azimuth", "azimuth_error", b"azimuth_error", "coordinate_system", b"coordinate_system", "datum", b"datum", "elevation", b"elevation", "elevation_error", b"elevation_error", "range", b"range", "range_error", b"range_error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_azimuth", b"_azimuth", "_azimuth_error", b"_azimuth_error", "_coordinate_system", b"_coordinate_system", "_datum", b"_datum", "_elevation", b"_elevation", "_elevation_error", b"_elevation_error", "_range", b"_range", "_range_error", b"_range_error", "azimuth", b"azimuth", "azimuth_error", b"azimuth_error", "coordinate_system", b"coordinate_system", "datum", b"datum", "elevation", b"elevation", "elevation_error", b"elevation_error", "range", b"range", "range_error", b"range_error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__azimuth: _TypeAlias = _typing.Literal["azimuth"]  # noqa: Y015
    _WhichOneofArgType__azimuth: _TypeAlias = _typing.Literal["_azimuth", b"_azimuth"]  # noqa: Y015
    _WhichOneofReturnType__azimuth_error: _TypeAlias = _typing.Literal["azimuth_error"]  # noqa: Y015
    _WhichOneofArgType__azimuth_error: _TypeAlias = _typing.Literal["_azimuth_error", b"_azimuth_error"]  # noqa: Y015
    _WhichOneofReturnType__coordinate_system: _TypeAlias = _typing.Literal["coordinate_system"]  # noqa: Y015
    _WhichOneofArgType__coordinate_system: _TypeAlias = _typing.Literal["_coordinate_system", b"_coordinate_system"]  # noqa: Y015
    _WhichOneofReturnType__datum: _TypeAlias = _typing.Literal["datum"]  # noqa: Y015
    _WhichOneofArgType__datum: _TypeAlias = _typing.Literal["_datum", b"_datum"]  # noqa: Y015
    _WhichOneofReturnType__elevation: _TypeAlias = _typing.Literal["elevation"]  # noqa: Y015
    _WhichOneofArgType__elevation: _TypeAlias = _typing.Literal["_elevation", b"_elevation"]  # noqa: Y015
    _WhichOneofReturnType__elevation_error: _TypeAlias = _typing.Literal["elevation_error"]  # noqa: Y015
    _WhichOneofArgType__elevation_error: _TypeAlias = _typing.Literal["_elevation_error", b"_elevation_error"]  # noqa: Y015
    _WhichOneofReturnType__range: _TypeAlias = _typing.Literal["range"]  # noqa: Y015
    _WhichOneofArgType__range: _TypeAlias = _typing.Literal["_range", b"_range"]  # noqa: Y015
    _WhichOneofReturnType__range_error: _TypeAlias = _typing.Literal["range_error"]  # noqa: Y015
    _WhichOneofArgType__range_error: _TypeAlias = _typing.Literal["_range_error", b"_range_error"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__azimuth) -> _WhichOneofReturnType__azimuth | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__azimuth_error) -> _WhichOneofReturnType__azimuth_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__coordinate_system) -> _WhichOneofReturnType__coordinate_system | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__datum) -> _WhichOneofReturnType__datum | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__elevation) -> _WhichOneofReturnType__elevation | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__elevation_error) -> _WhichOneofReturnType__elevation_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__range) -> _WhichOneofReturnType__range | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__range_error) -> _WhichOneofReturnType__range_error | None: ...

Global___RangeBearing: _TypeAlias = RangeBearing  # noqa: Y015

@_typing.final
class RangeBearingCone(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ELEVATION_FIELD_NUMBER: _builtins.int
    AZIMUTH_FIELD_NUMBER: _builtins.int
    RANGE_FIELD_NUMBER: _builtins.int
    HORIZONTAL_EXTENT_FIELD_NUMBER: _builtins.int
    VERTICAL_EXTENT_FIELD_NUMBER: _builtins.int
    HORIZONTAL_EXTENT_ERROR_FIELD_NUMBER: _builtins.int
    VERTICAL_EXTENT_ERROR_FIELD_NUMBER: _builtins.int
    ELEVATION_ERROR_FIELD_NUMBER: _builtins.int
    AZIMUTH_ERROR_FIELD_NUMBER: _builtins.int
    RANGE_ERROR_FIELD_NUMBER: _builtins.int
    COORDINATE_SYSTEM_FIELD_NUMBER: _builtins.int
    DATUM_FIELD_NUMBER: _builtins.int
    elevation: _builtins.float
    """Elevation in relation to node's horizon"""
    azimuth: _builtins.float
    """Azimuth in relation to the node's north"""
    range: _builtins.float
    """Range from the node's location"""
    horizontal_extent: _builtins.float
    """Horizontal extent angle in degrees"""
    vertical_extent: _builtins.float
    """Vertical extent angle in degrees"""
    horizontal_extent_error: _builtins.float
    """Error in the horizontal extent"""
    vertical_extent_error: _builtins.float
    """Error in the vertical extent"""
    elevation_error: _builtins.float
    """Elevation error"""
    azimuth_error: _builtins.float
    """Azimuth error"""
    range_error: _builtins.float
    """Range Error"""
    coordinate_system: Global___RangeBearingCoordinateSystem.ValueType
    """Units used by the range bearing"""
    datum: Global___RangeBearingDatum.ValueType
    """Datum or 'north' used by the range bearing"""
    def __init__(
        self,
        *,
        elevation: _builtins.float | None = ...,
        azimuth: _builtins.float | None = ...,
        range: _builtins.float | None = ...,
        horizontal_extent: _builtins.float | None = ...,
        vertical_extent: _builtins.float | None = ...,
        horizontal_extent_error: _builtins.float | None = ...,
        vertical_extent_error: _builtins.float | None = ...,
        elevation_error: _builtins.float | None = ...,
        azimuth_error: _builtins.float | None = ...,
        range_error: _builtins.float | None = ...,
        coordinate_system: Global___RangeBearingCoordinateSystem.ValueType | None = ...,
        datum: Global___RangeBearingDatum.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_azimuth", b"_azimuth", "_azimuth_error", b"_azimuth_error", "_coordinate_system", b"_coordinate_system", "_datum", b"_datum", "_elevation", b"_elevation", "_elevation_error", b"_elevation_error", "_horizontal_extent", b"_horizontal_extent", "_horizontal_extent_error", b"_horizontal_extent_error", "_range", b"_range", "_range_error", b"_range_error", "_vertical_extent", b"_vertical_extent", "_vertical_extent_error", b"_vertical_extent_error", "azimuth", b"azimuth", "azimuth_error", b"azimuth_error", "coordinate_system", b"coordinate_system", "datum", b"datum", "elevation", b"elevation", "elevation_error", b"elevation_error", "horizontal_extent", b"horizontal_extent", "horizontal_extent_error", b"horizontal_extent_error", "range", b"range", "range_error", b"range_error", "vertical_extent", b"vertical_extent", "vertical_extent_error", b"vertical_extent_error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_azimuth", b"_azimuth", "_azimuth_error", b"_azimuth_error", "_coordinate_system", b"_coordinate_system", "_datum", b"_datum", "_elevation", b"_elevation", "_elevation_error", b"_elevation_error", "_horizontal_extent", b"_horizontal_extent", "_horizontal_extent_error", b"_horizontal_extent_error", "_range", b"_range", "_range_error", b"_range_error", "_vertical_extent", b"_vertical_extent", "_vertical_extent_error", b"_vertical_extent_error", "azimuth", b"azimuth", "azimuth_error", b"azimuth_error", "coordinate_system", b"coordinate_system", "datum", b"datum", "elevation", b"elevation", "elevation_error", b"elevation_error", "horizontal_extent", b"horizontal_extent", "horizontal_extent_error", b"horizontal_extent_error", "range", b"range", "range_error", b"range_error", "vertical_extent", b"vertical_extent", "vertical_extent_error", b"vertical_extent_error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__azimuth: _TypeAlias = _typing.Literal["azimuth"]  # noqa: Y015
    _WhichOneofArgType__azimuth: _TypeAlias = _typing.Literal["_azimuth", b"_azimuth"]  # noqa: Y015
    _WhichOneofReturnType__azimuth_error: _TypeAlias = _typing.Literal["azimuth_error"]  # noqa: Y015
    _WhichOneofArgType__azimuth_error: _TypeAlias = _typing.Literal["_azimuth_error", b"_azimuth_error"]  # noqa: Y015
    _WhichOneofReturnType__coordinate_system: _TypeAlias = _typing.Literal["coordinate_system"]  # noqa: Y015
    _WhichOneofArgType__coordinate_system: _TypeAlias = _typing.Literal["_coordinate_system", b"_coordinate_system"]  # noqa: Y015
    _WhichOneofReturnType__datum: _TypeAlias = _typing.Literal["datum"]  # noqa: Y015
    _WhichOneofArgType__datum: _TypeAlias = _typing.Literal["_datum", b"_datum"]  # noqa: Y015
    _WhichOneofReturnType__elevation: _TypeAlias = _typing.Literal["elevation"]  # noqa: Y015
    _WhichOneofArgType__elevation: _TypeAlias = _typing.Literal["_elevation", b"_elevation"]  # noqa: Y015
    _WhichOneofReturnType__elevation_error: _TypeAlias = _typing.Literal["elevation_error"]  # noqa: Y015
    _WhichOneofArgType__elevation_error: _TypeAlias = _typing.Literal["_elevation_error", b"_elevation_error"]  # noqa: Y015
    _WhichOneofReturnType__horizontal_extent: _TypeAlias = _typing.Literal["horizontal_extent"]  # noqa: Y015
    _WhichOneofArgType__horizontal_extent: _TypeAlias = _typing.Literal["_horizontal_extent", b"_horizontal_extent"]  # noqa: Y015
    _WhichOneofReturnType__horizontal_extent_error: _TypeAlias = _typing.Literal["horizontal_extent_error"]  # noqa: Y015
    _WhichOneofArgType__horizontal_extent_error: _TypeAlias = _typing.Literal["_horizontal_extent_error", b"_horizontal_extent_error"]  # noqa: Y015
    _WhichOneofReturnType__range: _TypeAlias = _typing.Literal["range"]  # noqa: Y015
    _WhichOneofArgType__range: _TypeAlias = _typing.Literal["_range", b"_range"]  # noqa: Y015
    _WhichOneofReturnType__range_error: _TypeAlias = _typing.Literal["range_error"]  # noqa: Y015
    _WhichOneofArgType__range_error: _TypeAlias = _typing.Literal["_range_error", b"_range_error"]  # noqa: Y015
    _WhichOneofReturnType__vertical_extent: _TypeAlias = _typing.Literal["vertical_extent"]  # noqa: Y015
    _WhichOneofArgType__vertical_extent: _TypeAlias = _typing.Literal["_vertical_extent", b"_vertical_extent"]  # noqa: Y015
    _WhichOneofReturnType__vertical_extent_error: _TypeAlias = _typing.Literal["vertical_extent_error"]  # noqa: Y015
    _WhichOneofArgType__vertical_extent_error: _TypeAlias = _typing.Literal["_vertical_extent_error", b"_vertical_extent_error"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__azimuth) -> _WhichOneofReturnType__azimuth | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__azimuth_error) -> _WhichOneofReturnType__azimuth_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__coordinate_system) -> _WhichOneofReturnType__coordinate_system | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__datum) -> _WhichOneofReturnType__datum | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__elevation) -> _WhichOneofReturnType__elevation | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__elevation_error) -> _WhichOneofReturnType__elevation_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__horizontal_extent) -> _WhichOneofReturnType__horizontal_extent | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__horizontal_extent_error) -> _WhichOneofReturnType__horizontal_extent_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__range) -> _WhichOneofReturnType__range | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__range_error) -> _WhichOneofReturnType__range_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__vertical_extent) -> _WhichOneofReturnType__vertical_extent | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__vertical_extent_error) -> _WhichOneofReturnType__vertical_extent_error | None: ...

Global___RangeBearingCone: _TypeAlias = RangeBearingCone  # noqa: Y015

@_typing.final
class LocationOrRangeBearing(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RANGE_BEARING_FIELD_NUMBER: _builtins.int
    LOCATION_LIST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def range_bearing(self) -> Global___RangeBearingCone:
        """Location in Spherical coordinates"""

    @_builtins.property
    def location_list(self) -> _location_pb2.LocationList:
        """Location in Geo coordinates"""

    def __init__(
        self,
        *,
        range_bearing: Global___RangeBearingCone | None = ...,
        location_list: _location_pb2.LocationList | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fov_oneof", b"fov_oneof", "location_list", b"location_list", "range_bearing", b"range_bearing"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fov_oneof", b"fov_oneof", "location_list", b"location_list", "range_bearing", b"range_bearing"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_fov_oneof: _TypeAlias = _typing.Literal["range_bearing", "location_list"]  # noqa: Y015
    _WhichOneofArgType_fov_oneof: _TypeAlias = _typing.Literal["fov_oneof", b"fov_oneof"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_fov_oneof) -> _WhichOneofReturnType_fov_oneof | None: ...

Global___LocationOrRangeBearing: _TypeAlias = LocationOrRangeBearing  # noqa: Y015
