"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RegistrationAck(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTANCE_FIELD_NUMBER: _builtins.int
    ACK_RESPONSE_REASON_FIELD_NUMBER: _builtins.int
    acceptance: _builtins.bool
    """This value shall be 0 if the registration is rejected, or 1 if the registration is accepted"""
    @_builtins.property
    def ack_response_reason(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """ optional string ack_response_reason = 2; // This field can be used to communicate the reason for non-registration
        This field can be used to communicate the (operational) reason(s) for rejecting the Registration Message (one per array element)
        """

    def __init__(
        self,
        *,
        acceptance: _builtins.bool | None = ...,
        ack_response_reason: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_acceptance", b"_acceptance", "acceptance", b"acceptance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_acceptance", b"_acceptance", "acceptance", b"acceptance", "ack_response_reason", b"ack_response_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__acceptance: _TypeAlias = _typing.Literal["acceptance"]  # noqa: Y015
    _WhichOneofArgType__acceptance: _TypeAlias = _typing.Literal["_acceptance", b"_acceptance"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__acceptance) -> _WhichOneofReturnType__acceptance | None: ...

Global___RegistrationAck: _TypeAlias = RegistrationAck  # noqa: Y015
