"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from sapient_msg.bsi_flex_335_v2_0 import alert_ack_pb2 as _alert_ack_pb2
from sapient_msg.bsi_flex_335_v2_0 import alert_pb2 as _alert_pb2
from sapient_msg.bsi_flex_335_v2_0 import detection_report_pb2 as _detection_report_pb2
from sapient_msg.bsi_flex_335_v2_0 import error_pb2 as _error_pb2
from sapient_msg.bsi_flex_335_v2_0 import registration_ack_pb2 as _registration_ack_pb2
from sapient_msg.bsi_flex_335_v2_0 import registration_pb2 as _registration_pb2
from sapient_msg.bsi_flex_335_v2_0 import status_report_pb2 as _status_report_pb2
from sapient_msg.bsi_flex_335_v2_0 import task_ack_pb2 as _task_ack_pb2
from sapient_msg.bsi_flex_335_v2_0 import task_pb2 as _task_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SapientMessage(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    NODE_ID_FIELD_NUMBER: _builtins.int
    DESTINATION_ID_FIELD_NUMBER: _builtins.int
    REGISTRATION_FIELD_NUMBER: _builtins.int
    REGISTRATION_ACK_FIELD_NUMBER: _builtins.int
    STATUS_REPORT_FIELD_NUMBER: _builtins.int
    DETECTION_REPORT_FIELD_NUMBER: _builtins.int
    TASK_FIELD_NUMBER: _builtins.int
    TASK_ACK_FIELD_NUMBER: _builtins.int
    ALERT_FIELD_NUMBER: _builtins.int
    ALERT_ACK_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    ADDITIONAL_INFORMATION_FIELD_NUMBER: _builtins.int
    node_id: _builtins.str
    """UUID for the node which is sending the message"""
    destination_id: _builtins.str
    """UUID for the node being tasked"""
    additional_information: _builtins.str
    """space for additional information"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp the message was sent"""

    @_builtins.property
    def registration(self) -> _registration_pb2.Registration:
        """SAPIENT Registration message"""

    @_builtins.property
    def registration_ack(self) -> _registration_ack_pb2.RegistrationAck:
        """SAPIENT Registration Acknowledgement message"""

    @_builtins.property
    def status_report(self) -> _status_report_pb2.StatusReport:
        """SAPIENT Status Report message"""

    @_builtins.property
    def detection_report(self) -> _detection_report_pb2.DetectionReport:
        """SAPIENT Detection Report message"""

    @_builtins.property
    def task(self) -> _task_pb2.Task:
        """SAPIENT Task message"""

    @_builtins.property
    def task_ack(self) -> _task_ack_pb2.TaskAck:
        """SAPIENT Task Acknowledgement message"""

    @_builtins.property
    def alert(self) -> _alert_pb2.Alert:
        """SAPIENT Alert message"""

    @_builtins.property
    def alert_ack(self) -> _alert_ack_pb2.AlertAck:
        """SAPIENT Alert Acknowledgment message"""

    @_builtins.property
    def error(self) -> _error_pb2.Error:
        """SAPIENT Error message"""

    def __init__(
        self,
        *,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        node_id: _builtins.str | None = ...,
        destination_id: _builtins.str | None = ...,
        registration: _registration_pb2.Registration | None = ...,
        registration_ack: _registration_ack_pb2.RegistrationAck | None = ...,
        status_report: _status_report_pb2.StatusReport | None = ...,
        detection_report: _detection_report_pb2.DetectionReport | None = ...,
        task: _task_pb2.Task | None = ...,
        task_ack: _task_ack_pb2.TaskAck | None = ...,
        alert: _alert_pb2.Alert | None = ...,
        alert_ack: _alert_ack_pb2.AlertAck | None = ...,
        error: _error_pb2.Error | None = ...,
        additional_information: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_additional_information", b"_additional_information", "_destination_id", b"_destination_id", "_node_id", b"_node_id", "_timestamp", b"_timestamp", "additional_information", b"additional_information", "alert", b"alert", "alert_ack", b"alert_ack", "content", b"content", "destination_id", b"destination_id", "detection_report", b"detection_report", "error", b"error", "node_id", b"node_id", "registration", b"registration", "registration_ack", b"registration_ack", "status_report", b"status_report", "task", b"task", "task_ack", b"task_ack", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_additional_information", b"_additional_information", "_destination_id", b"_destination_id", "_node_id", b"_node_id", "_timestamp", b"_timestamp", "additional_information", b"additional_information", "alert", b"alert", "alert_ack", b"alert_ack", "content", b"content", "destination_id", b"destination_id", "detection_report", b"detection_report", "error", b"error", "node_id", b"node_id", "registration", b"registration", "registration_ack", b"registration_ack", "status_report", b"status_report", "task", b"task", "task_ack", b"task_ack", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__additional_information: _TypeAlias = _typing.Literal["additional_information"]  # noqa: Y015
    _WhichOneofArgType__additional_information: _TypeAlias = _typing.Literal["_additional_information", b"_additional_information"]  # noqa: Y015
    _WhichOneofReturnType__destination_id: _TypeAlias = _typing.Literal["destination_id"]  # noqa: Y015
    _WhichOneofArgType__destination_id: _TypeAlias = _typing.Literal["_destination_id", b"_destination_id"]  # noqa: Y015
    _WhichOneofReturnType__node_id: _TypeAlias = _typing.Literal["node_id"]  # noqa: Y015
    _WhichOneofArgType__node_id: _TypeAlias = _typing.Literal["_node_id", b"_node_id"]  # noqa: Y015
    _WhichOneofReturnType__timestamp: _TypeAlias = _typing.Literal["timestamp"]  # noqa: Y015
    _WhichOneofArgType__timestamp: _TypeAlias = _typing.Literal["_timestamp", b"_timestamp"]  # noqa: Y015
    _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["registration", "registration_ack", "status_report", "detection_report", "task", "task_ack", "alert", "alert_ack", "error"]  # noqa: Y015
    _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__additional_information) -> _WhichOneofReturnType__additional_information | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__destination_id) -> _WhichOneofReturnType__destination_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__node_id) -> _WhichOneofReturnType__node_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timestamp) -> _WhichOneofReturnType__timestamp | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

Global___SapientMessage: _TypeAlias = SapientMessage  # noqa: Y015
