"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sapient_msg.bsi_flex_335_v2_0 import location_pb2 as _location_pb2
from sapient_msg.bsi_flex_335_v2_0 import range_bearing_pb2 as _range_bearing_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StatusReport(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    class _System:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SystemEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StatusReport._System.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SYSTEM_UNSPECIFIED: StatusReport._System.ValueType  # 0
        """The system state is unset"""
        SYSTEM_OK: StatusReport._System.ValueType  # 1
        """The system is operating normally"""
        SYSTEM_WARNING: StatusReport._System.ValueType  # 2
        """There is a potential issue with the system"""
        SYSTEM_ERROR: StatusReport._System.ValueType  # 3
        """There is an issue with the system"""
        SYSTEM_GOODBYE: StatusReport._System.ValueType  # 5
        """       SYSTEM_TAMPER = 4; // The system has been tampered with - DEPRECIATED
        The system is about to disconnect
        """

    class System(_System, metaclass=_SystemEnumTypeWrapper): ...
    SYSTEM_UNSPECIFIED: StatusReport.System.ValueType  # 0
    """The system state is unset"""
    SYSTEM_OK: StatusReport.System.ValueType  # 1
    """The system is operating normally"""
    SYSTEM_WARNING: StatusReport.System.ValueType  # 2
    """There is a potential issue with the system"""
    SYSTEM_ERROR: StatusReport.System.ValueType  # 3
    """There is an issue with the system"""
    SYSTEM_GOODBYE: StatusReport.System.ValueType  # 5
    """       SYSTEM_TAMPER = 4; // The system has been tampered with - DEPRECIATED
    The system is about to disconnect
    """

    class _PowerSource:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PowerSourceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StatusReport._PowerSource.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        POWERSOURCE_UNSPECIFIED: StatusReport._PowerSource.ValueType  # 0
        """The PowerSource is unset"""
        POWERSOURCE_OTHER: StatusReport._PowerSource.ValueType  # 1
        """The power source is of a different type listed in this enumeration"""
        POWERSOURCE_MAINS: StatusReport._PowerSource.ValueType  # 2
        """The power source is the mains (fixed infrastructure)"""
        POWERSOURCE_INTERNAL_BATTERY: StatusReport._PowerSource.ValueType  # 3
        """The power source is a battery contained within the node"""
        POWERSOURCE_EXTERNAL_BATTERY: StatusReport._PowerSource.ValueType  # 4
        """The power source is a battery external to the node"""
        POWERSOURCE_GENERATOR: StatusReport._PowerSource.ValueType  # 5
        """The power source is a generator"""
        POWERSOURCE_SOLAR_PV: StatusReport._PowerSource.ValueType  # 6
        """The power source is a solar photovoltaic panel/array"""
        POWERSOURCE_WIND_TURBINE: StatusReport._PowerSource.ValueType  # 7
        """The power source is a wind turbine"""
        POWERSOURCE_FUEL_CELL: StatusReport._PowerSource.ValueType  # 8
        """The power source is a fuel cell"""

    class PowerSource(_PowerSource, metaclass=_PowerSourceEnumTypeWrapper): ...
    POWERSOURCE_UNSPECIFIED: StatusReport.PowerSource.ValueType  # 0
    """The PowerSource is unset"""
    POWERSOURCE_OTHER: StatusReport.PowerSource.ValueType  # 1
    """The power source is of a different type listed in this enumeration"""
    POWERSOURCE_MAINS: StatusReport.PowerSource.ValueType  # 2
    """The power source is the mains (fixed infrastructure)"""
    POWERSOURCE_INTERNAL_BATTERY: StatusReport.PowerSource.ValueType  # 3
    """The power source is a battery contained within the node"""
    POWERSOURCE_EXTERNAL_BATTERY: StatusReport.PowerSource.ValueType  # 4
    """The power source is a battery external to the node"""
    POWERSOURCE_GENERATOR: StatusReport.PowerSource.ValueType  # 5
    """The power source is a generator"""
    POWERSOURCE_SOLAR_PV: StatusReport.PowerSource.ValueType  # 6
    """The power source is a solar photovoltaic panel/array"""
    POWERSOURCE_WIND_TURBINE: StatusReport.PowerSource.ValueType  # 7
    """The power source is a wind turbine"""
    POWERSOURCE_FUEL_CELL: StatusReport.PowerSource.ValueType  # 8
    """The power source is a fuel cell"""

    class _PowerStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PowerStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StatusReport._PowerStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        POWERSTATUS_UNSPECIFIED: StatusReport._PowerStatus.ValueType  # 0
        """The PowerStatus is unset"""
        POWERSTATUS_OK: StatusReport._PowerStatus.ValueType  # 1
        """The power status is normal"""
        POWERSTATUS_FAULT: StatusReport._PowerStatus.ValueType  # 2
        """There is a fault with the power source"""

    class PowerStatus(_PowerStatus, metaclass=_PowerStatusEnumTypeWrapper): ...
    POWERSTATUS_UNSPECIFIED: StatusReport.PowerStatus.ValueType  # 0
    """The PowerStatus is unset"""
    POWERSTATUS_OK: StatusReport.PowerStatus.ValueType  # 1
    """The power status is normal"""
    POWERSTATUS_FAULT: StatusReport.PowerStatus.ValueType  # 2
    """There is a fault with the power source"""

    class _Info:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _InfoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StatusReport._Info.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        INFO_UNSPECIFIED: StatusReport._Info.ValueType  # 0
        """Unset enum"""
        INFO_NEW: StatusReport._Info.ValueType  # 1
        """New information about the system is being presented"""
        INFO_UNCHANGED: StatusReport._Info.ValueType  # 2
        """The existing information about the system is up-to-date"""

    class Info(_Info, metaclass=_InfoEnumTypeWrapper): ...
    INFO_UNSPECIFIED: StatusReport.Info.ValueType  # 0
    """Unset enum"""
    INFO_NEW: StatusReport.Info.ValueType  # 1
    """New information about the system is being presented"""
    INFO_UNCHANGED: StatusReport.Info.ValueType  # 2
    """The existing information about the system is up-to-date"""

    class _StatusType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StatusReport._StatusType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_TYPE_UNSPECIFIED: StatusReport._StatusType.ValueType  # 0
        """No status type has been set"""
        STATUS_TYPE_INTERNAL_FAULT: StatusReport._StatusType.ValueType  # 1
        """The node has an internal fault"""
        STATUS_TYPE_EXTERNAL_FAULT: StatusReport._StatusType.ValueType  # 2
        """External influences have caused a fault with the node"""
        STATUS_TYPE_ILLUMINATION: StatusReport._StatusType.ValueType  # 3
        """"""
        STATUS_TYPE_WEATHER: StatusReport._StatusType.ValueType  # 4
        """"""
        STATUS_TYPE_CLUTTER: StatusReport._StatusType.ValueType  # 5
        """"""
        STATUS_TYPE_EXPOSURE: StatusReport._StatusType.ValueType  # 6
        """"""
        STATUS_TYPE_MOTION_SENSITIVITY: StatusReport._StatusType.ValueType  # 7
        """"""
        STATUS_TYPE_PTZ_STATUS: StatusReport._StatusType.ValueType  # 8
        """"""
        STATUS_TYPE_PD: StatusReport._StatusType.ValueType  # 9
        """"""
        STATUS_TYPE_FAR: StatusReport._StatusType.ValueType  # 10
        """"""
        STATUS_TYPE_NOT_DETECTING: StatusReport._StatusType.ValueType  # 11
        """The node is not detecting"""
        STATUS_TYPE_PLATFORM: StatusReport._StatusType.ValueType  # 12
        """A report about a platform node"""
        STATUS_TYPE_OTHER: StatusReport._StatusType.ValueType  # 13
        """"""

    class StatusType(_StatusType, metaclass=_StatusTypeEnumTypeWrapper): ...
    STATUS_TYPE_UNSPECIFIED: StatusReport.StatusType.ValueType  # 0
    """No status type has been set"""
    STATUS_TYPE_INTERNAL_FAULT: StatusReport.StatusType.ValueType  # 1
    """The node has an internal fault"""
    STATUS_TYPE_EXTERNAL_FAULT: StatusReport.StatusType.ValueType  # 2
    """External influences have caused a fault with the node"""
    STATUS_TYPE_ILLUMINATION: StatusReport.StatusType.ValueType  # 3
    """"""
    STATUS_TYPE_WEATHER: StatusReport.StatusType.ValueType  # 4
    """"""
    STATUS_TYPE_CLUTTER: StatusReport.StatusType.ValueType  # 5
    """"""
    STATUS_TYPE_EXPOSURE: StatusReport.StatusType.ValueType  # 6
    """"""
    STATUS_TYPE_MOTION_SENSITIVITY: StatusReport.StatusType.ValueType  # 7
    """"""
    STATUS_TYPE_PTZ_STATUS: StatusReport.StatusType.ValueType  # 8
    """"""
    STATUS_TYPE_PD: StatusReport.StatusType.ValueType  # 9
    """"""
    STATUS_TYPE_FAR: StatusReport.StatusType.ValueType  # 10
    """"""
    STATUS_TYPE_NOT_DETECTING: StatusReport.StatusType.ValueType  # 11
    """The node is not detecting"""
    STATUS_TYPE_PLATFORM: StatusReport.StatusType.ValueType  # 12
    """A report about a platform node"""
    STATUS_TYPE_OTHER: StatusReport.StatusType.ValueType  # 13
    """"""

    class _StatusLevel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StatusReport._StatusLevel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_LEVEL_UNSPECIFIED: StatusReport._StatusLevel.ValueType  # 0
        """No status level has been set"""
        STATUS_LEVEL_INFORMATION_STATUS: StatusReport._StatusLevel.ValueType  # 2
        """STATUS_LEVEL_SENSOR_STATUS = 1; // Information about the current node state
        Information about the environment that might affect this or other nodes
        """
        STATUS_LEVEL_WARNING_STATUS: StatusReport._StatusLevel.ValueType  # 3
        """Information about performance degregation of the node"""
        STATUS_LEVEL_ERROR_STATUS: StatusReport._StatusLevel.ValueType  # 4
        """Information about severely affecting this node's capabilities"""

    class StatusLevel(_StatusLevel, metaclass=_StatusLevelEnumTypeWrapper): ...
    STATUS_LEVEL_UNSPECIFIED: StatusReport.StatusLevel.ValueType  # 0
    """No status level has been set"""
    STATUS_LEVEL_INFORMATION_STATUS: StatusReport.StatusLevel.ValueType  # 2
    """STATUS_LEVEL_SENSOR_STATUS = 1; // Information about the current node state
    Information about the environment that might affect this or other nodes
    """
    STATUS_LEVEL_WARNING_STATUS: StatusReport.StatusLevel.ValueType  # 3
    """Information about performance degregation of the node"""
    STATUS_LEVEL_ERROR_STATUS: StatusReport.StatusLevel.ValueType  # 4
    """Information about severely affecting this node's capabilities"""

    @_typing.final
    class Power(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LEVEL_FIELD_NUMBER: _builtins.int
        SOURCE_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        level: _builtins.int
        """       optional string source = 1; // Power source (e.g. battery/mains)
               optional string status = 2; // Power supply status
        Battery level 0-100
        """
        source: Global___StatusReport.PowerSource.ValueType
        """The power source being used by the node"""
        status: Global___StatusReport.PowerStatus.ValueType
        """The status of the power source being used by the node"""
        def __init__(
            self,
            *,
            level: _builtins.int | None = ...,
            source: Global___StatusReport.PowerSource.ValueType = ...,
            status: Global___StatusReport.PowerStatus.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_level", b"_level", "level", b"level"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_level", b"_level", "level", b"level", "source", b"source", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__level: _TypeAlias = _typing.Literal["level"]  # noqa: Y015
        _WhichOneofArgType__level: _TypeAlias = _typing.Literal["_level", b"_level"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__level) -> _WhichOneofReturnType__level | None: ...

    @_typing.final
    class Status(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_LEVEL_FIELD_NUMBER: _builtins.int
        STATUS_VALUE_FIELD_NUMBER: _builtins.int
        STATUS_TYPE_FIELD_NUMBER: _builtins.int
        status_level: Global___StatusReport.StatusLevel.ValueType
        """Information level being reported"""
        status_value: _builtins.str
        """       optional string status_type = 2 [(field_options) = {is_mandatory: true}]; // Type of the information being reported (e.g. Weather)
        Value of the information being reported (e.g. Raining)
        """
        status_type: Global___StatusReport.StatusType.ValueType
        """Type of the information being reported (e.g. Weather)"""
        def __init__(
            self,
            *,
            status_level: Global___StatusReport.StatusLevel.ValueType | None = ...,
            status_value: _builtins.str | None = ...,
            status_type: Global___StatusReport.StatusType.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_status_level", b"_status_level", "_status_type", b"_status_type", "_status_value", b"_status_value", "status_level", b"status_level", "status_type", b"status_type", "status_value", b"status_value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_status_level", b"_status_level", "_status_type", b"_status_type", "_status_value", b"_status_value", "status_level", b"status_level", "status_type", b"status_type", "status_value", b"status_value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__status_level: _TypeAlias = _typing.Literal["status_level"]  # noqa: Y015
        _WhichOneofArgType__status_level: _TypeAlias = _typing.Literal["_status_level", b"_status_level"]  # noqa: Y015
        _WhichOneofReturnType__status_type: _TypeAlias = _typing.Literal["status_type"]  # noqa: Y015
        _WhichOneofArgType__status_type: _TypeAlias = _typing.Literal["_status_type", b"_status_type"]  # noqa: Y015
        _WhichOneofReturnType__status_value: _TypeAlias = _typing.Literal["status_value"]  # noqa: Y015
        _WhichOneofArgType__status_value: _TypeAlias = _typing.Literal["_status_value", b"_status_value"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__status_level) -> _WhichOneofReturnType__status_level | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__status_type) -> _WhichOneofReturnType__status_type | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__status_value) -> _WhichOneofReturnType__status_value | None: ...

    REPORT_ID_FIELD_NUMBER: _builtins.int
    SYSTEM_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    ACTIVE_TASK_ID_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    POWER_FIELD_NUMBER: _builtins.int
    NODE_LOCATION_FIELD_NUMBER: _builtins.int
    FIELD_OF_VIEW_FIELD_NUMBER: _builtins.int
    OBSCURATION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    COVERAGE_FIELD_NUMBER: _builtins.int
    report_id: _builtins.str
    """ULID for the message"""
    system: Global___StatusReport.System.ValueType
    """Current ASM status"""
    info: Global___StatusReport.Info.ValueType
    """State of the information in this message"""
    active_task_id: _builtins.str
    """ULID of the task the ASM is currently performing"""
    mode: _builtins.str
    """The current mode of the ASM"""
    @_builtins.property
    def power(self) -> Global___StatusReport.Power:
        """The power supply of the ASM"""

    @_builtins.property
    def node_location(self) -> _location_pb2.Location:
        """Current ASM location"""

    @_builtins.property
    def field_of_view(self) -> _range_bearing_pb2.LocationOrRangeBearing:
        """Area currently visible to ASM"""

    @_builtins.property
    def obscuration(self) -> _containers.RepeatedCompositeFieldContainer[_range_bearing_pb2.LocationOrRangeBearing]:
        """   optional LocationOrRangeBearing coverage = 9; // Area that the ASM can cover
        Area that the ASM cannot cover
        """

    @_builtins.property
    def status(self) -> _containers.RepeatedCompositeFieldContainer[Global___StatusReport.Status]:
        """Information about the ASM or the envionrment"""

    @_builtins.property
    def coverage(self) -> _containers.RepeatedCompositeFieldContainer[_range_bearing_pb2.LocationOrRangeBearing]:
        """The coverage field has been made repeated so that a Fusion Node can report the total coverage from its child/edge nodes"""

    def __init__(
        self,
        *,
        report_id: _builtins.str | None = ...,
        system: Global___StatusReport.System.ValueType | None = ...,
        info: Global___StatusReport.Info.ValueType | None = ...,
        active_task_id: _builtins.str | None = ...,
        mode: _builtins.str | None = ...,
        power: Global___StatusReport.Power | None = ...,
        node_location: _location_pb2.Location | None = ...,
        field_of_view: _range_bearing_pb2.LocationOrRangeBearing | None = ...,
        obscuration: _abc.Iterable[_range_bearing_pb2.LocationOrRangeBearing] | None = ...,
        status: _abc.Iterable[Global___StatusReport.Status] | None = ...,
        coverage: _abc.Iterable[_range_bearing_pb2.LocationOrRangeBearing] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_active_task_id", b"_active_task_id", "_field_of_view", b"_field_of_view", "_info", b"_info", "_mode", b"_mode", "_node_location", b"_node_location", "_power", b"_power", "_report_id", b"_report_id", "_system", b"_system", "active_task_id", b"active_task_id", "field_of_view", b"field_of_view", "info", b"info", "mode", b"mode", "node_location", b"node_location", "power", b"power", "report_id", b"report_id", "system", b"system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_active_task_id", b"_active_task_id", "_field_of_view", b"_field_of_view", "_info", b"_info", "_mode", b"_mode", "_node_location", b"_node_location", "_power", b"_power", "_report_id", b"_report_id", "_system", b"_system", "active_task_id", b"active_task_id", "coverage", b"coverage", "field_of_view", b"field_of_view", "info", b"info", "mode", b"mode", "node_location", b"node_location", "obscuration", b"obscuration", "power", b"power", "report_id", b"report_id", "status", b"status", "system", b"system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__active_task_id: _TypeAlias = _typing.Literal["active_task_id"]  # noqa: Y015
    _WhichOneofArgType__active_task_id: _TypeAlias = _typing.Literal["_active_task_id", b"_active_task_id"]  # noqa: Y015
    _WhichOneofReturnType__field_of_view: _TypeAlias = _typing.Literal["field_of_view"]  # noqa: Y015
    _WhichOneofArgType__field_of_view: _TypeAlias = _typing.Literal["_field_of_view", b"_field_of_view"]  # noqa: Y015
    _WhichOneofReturnType__info: _TypeAlias = _typing.Literal["info"]  # noqa: Y015
    _WhichOneofArgType__info: _TypeAlias = _typing.Literal["_info", b"_info"]  # noqa: Y015
    _WhichOneofReturnType__mode: _TypeAlias = _typing.Literal["mode"]  # noqa: Y015
    _WhichOneofArgType__mode: _TypeAlias = _typing.Literal["_mode", b"_mode"]  # noqa: Y015
    _WhichOneofReturnType__node_location: _TypeAlias = _typing.Literal["node_location"]  # noqa: Y015
    _WhichOneofArgType__node_location: _TypeAlias = _typing.Literal["_node_location", b"_node_location"]  # noqa: Y015
    _WhichOneofReturnType__power: _TypeAlias = _typing.Literal["power"]  # noqa: Y015
    _WhichOneofArgType__power: _TypeAlias = _typing.Literal["_power", b"_power"]  # noqa: Y015
    _WhichOneofReturnType__report_id: _TypeAlias = _typing.Literal["report_id"]  # noqa: Y015
    _WhichOneofArgType__report_id: _TypeAlias = _typing.Literal["_report_id", b"_report_id"]  # noqa: Y015
    _WhichOneofReturnType__system: _TypeAlias = _typing.Literal["system"]  # noqa: Y015
    _WhichOneofArgType__system: _TypeAlias = _typing.Literal["_system", b"_system"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__active_task_id) -> _WhichOneofReturnType__active_task_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__field_of_view) -> _WhichOneofReturnType__field_of_view | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__info) -> _WhichOneofReturnType__info | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__mode) -> _WhichOneofReturnType__mode | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__node_location) -> _WhichOneofReturnType__node_location | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__power) -> _WhichOneofReturnType__power | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__report_id) -> _WhichOneofReturnType__report_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__system) -> _WhichOneofReturnType__system | None: ...

Global___StatusReport: _TypeAlias = StatusReport  # noqa: Y015
