"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sapient_msg.bsi_flex_335_v2_0 import associated_file_pb2 as _associated_file_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TaskAck(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    class _TaskStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TaskStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TaskAck._TaskStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TASK_STATUS_UNSPECIFIED: TaskAck._TaskStatus.ValueType  # 0
        """Unset enum"""
        TASK_STATUS_ACCEPTED: TaskAck._TaskStatus.ValueType  # 1
        """Task was accepted"""
        TASK_STATUS_REJECTED: TaskAck._TaskStatus.ValueType  # 2
        """Task was rejected (reason should also be present in the message)"""
        TASK_STATUS_COMPLETED: TaskAck._TaskStatus.ValueType  # 3
        """Task has been completed"""
        TASK_STATUS_FAILED: TaskAck._TaskStatus.ValueType  # 4
        """A node has previously accepted a task but has been unable to successfully complete it."""

    class TaskStatus(_TaskStatus, metaclass=_TaskStatusEnumTypeWrapper): ...
    TASK_STATUS_UNSPECIFIED: TaskAck.TaskStatus.ValueType  # 0
    """Unset enum"""
    TASK_STATUS_ACCEPTED: TaskAck.TaskStatus.ValueType  # 1
    """Task was accepted"""
    TASK_STATUS_REJECTED: TaskAck.TaskStatus.ValueType  # 2
    """Task was rejected (reason should also be present in the message)"""
    TASK_STATUS_COMPLETED: TaskAck.TaskStatus.ValueType  # 3
    """Task has been completed"""
    TASK_STATUS_FAILED: TaskAck.TaskStatus.ValueType  # 4
    """A node has previously accepted a task but has been unable to successfully complete it."""

    TASK_ID_FIELD_NUMBER: _builtins.int
    TASK_STATUS_FIELD_NUMBER: _builtins.int
    ASSOCIATED_FILE_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """ULID of task that is being acknowledged"""
    task_status: Global___TaskAck.TaskStatus.ValueType
    """Status of the task (accepted or rejected)"""
    @_builtins.property
    def associated_file(self) -> _associated_file_pb2.AssociatedFile:
        """ optional string reason = 3; // Reason for the rejection if task is rejected or completed
        File associated with task being acknowledged
        """

    @_builtins.property
    def reason(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Reason(s) for the rejection if task is rejected, completed, or failed"""

    def __init__(
        self,
        *,
        task_id: _builtins.str | None = ...,
        task_status: Global___TaskAck.TaskStatus.ValueType | None = ...,
        associated_file: _associated_file_pb2.AssociatedFile | None = ...,
        reason: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_associated_file", b"_associated_file", "_task_id", b"_task_id", "_task_status", b"_task_status", "associated_file", b"associated_file", "task_id", b"task_id", "task_status", b"task_status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_associated_file", b"_associated_file", "_task_id", b"_task_id", "_task_status", b"_task_status", "associated_file", b"associated_file", "reason", b"reason", "task_id", b"task_id", "task_status", b"task_status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__associated_file: _TypeAlias = _typing.Literal["associated_file"]  # noqa: Y015
    _WhichOneofArgType__associated_file: _TypeAlias = _typing.Literal["_associated_file", b"_associated_file"]  # noqa: Y015
    _WhichOneofReturnType__task_id: _TypeAlias = _typing.Literal["task_id"]  # noqa: Y015
    _WhichOneofArgType__task_id: _TypeAlias = _typing.Literal["_task_id", b"_task_id"]  # noqa: Y015
    _WhichOneofReturnType__task_status: _TypeAlias = _typing.Literal["task_status"]  # noqa: Y015
    _WhichOneofArgType__task_status: _TypeAlias = _typing.Literal["_task_status", b"_task_status"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__associated_file) -> _WhichOneofReturnType__associated_file | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_id) -> _WhichOneofReturnType__task_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_status) -> _WhichOneofReturnType__task_status | None: ...

Global___TaskAck: _TypeAlias = TaskAck  # noqa: Y015
