"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sapient_msg.bsi_flex_335_v2_0 import follow_pb2 as _follow_pb2
from sapient_msg.bsi_flex_335_v2_0 import location_pb2 as _location_pb2
from sapient_msg.bsi_flex_335_v2_0 import range_bearing_pb2 as _range_bearing_pb2
from sapient_msg.bsi_flex_335_v2_0 import registration_pb2 as _registration_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Task(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    class _Control:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ControlEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Task._Control.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CONTROL_UNSPECIFIED: Task._Control.ValueType  # 0
        """No control set"""
        CONTROL_START: Task._Control.ValueType  # 1
        """Initialise/start the task"""
        CONTROL_STOP: Task._Control.ValueType  # 2
        """Stop the task, remove the definition and revert to the previous task"""
        CONTROL_PAUSE: Task._Control.ValueType  # 3
        """Stop the task, keep the definition for later use and revert to previous task"""

    class Control(_Control, metaclass=_ControlEnumTypeWrapper): ...
    CONTROL_UNSPECIFIED: Task.Control.ValueType  # 0
    """No control set"""
    CONTROL_START: Task.Control.ValueType  # 1
    """Initialise/start the task"""
    CONTROL_STOP: Task.Control.ValueType  # 2
    """Stop the task, remove the definition and revert to the previous task"""
    CONTROL_PAUSE: Task.Control.ValueType  # 3
    """Stop the task, keep the definition for later use and revert to previous task"""

    class _DiscreteThreshold:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DiscreteThresholdEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Task._DiscreteThreshold.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DISCRETE_THRESHOLD_UNSPECIFIED: Task._DiscreteThreshold.ValueType  # 0
        """Threshold not set"""
        DISCRETE_THRESHOLD_LOW: Task._DiscreteThreshold.ValueType  # 1
        """Threshold set to low"""
        DISCRETE_THRESHOLD_MEDIUM: Task._DiscreteThreshold.ValueType  # 2
        """Threshold set to medium"""
        DISCRETE_THRESHOLD_HIGH: Task._DiscreteThreshold.ValueType  # 3
        """Threshold set to high"""

    class DiscreteThreshold(_DiscreteThreshold, metaclass=_DiscreteThresholdEnumTypeWrapper): ...
    DISCRETE_THRESHOLD_UNSPECIFIED: Task.DiscreteThreshold.ValueType  # 0
    """Threshold not set"""
    DISCRETE_THRESHOLD_LOW: Task.DiscreteThreshold.ValueType  # 1
    """Threshold set to low"""
    DISCRETE_THRESHOLD_MEDIUM: Task.DiscreteThreshold.ValueType  # 2
    """Threshold set to medium"""
    DISCRETE_THRESHOLD_HIGH: Task.DiscreteThreshold.ValueType  # 3
    """Threshold set to high"""

    class _RegionType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RegionTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Task._RegionType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        REGION_TYPE_UNSPECIFIED: Task._RegionType.ValueType  # 0
        """No region type set"""
        REGION_TYPE_AREA_OF_INTEREST: Task._RegionType.ValueType  # 1
        """Region is of particular interest"""
        REGION_TYPE_IGNORE: Task._RegionType.ValueType  # 2
        """Region to be ignored"""
        REGION_TYPE_BOUNDARY: Task._RegionType.ValueType  # 3
        """Region defines the boundary of the area of operations"""
        REGION_TYPE_MOBILE_NODE_NO_GO_AREA: Task._RegionType.ValueType  # 4
        """Region defines an area that mobile nodes shall not enter"""
        REGION_TYPE_MOBILE_NODE_GO_AREA: Task._RegionType.ValueType  # 5
        """Region defines an area that mobile nodes shall remain within"""

    class RegionType(_RegionType, metaclass=_RegionTypeEnumTypeWrapper):
        """
        Note: enum RegionType also features in registration.proto, if making changes to this enumeration, identical changes must be made
        in the same enumeration in registration.proto. Users should be aware, future versions of the SAPIENT proto files may be 
        restructured so that enum RegionType only appears once.
        """

    REGION_TYPE_UNSPECIFIED: Task.RegionType.ValueType  # 0
    """No region type set"""
    REGION_TYPE_AREA_OF_INTEREST: Task.RegionType.ValueType  # 1
    """Region is of particular interest"""
    REGION_TYPE_IGNORE: Task.RegionType.ValueType  # 2
    """Region to be ignored"""
    REGION_TYPE_BOUNDARY: Task.RegionType.ValueType  # 3
    """Region defines the boundary of the area of operations"""
    REGION_TYPE_MOBILE_NODE_NO_GO_AREA: Task.RegionType.ValueType  # 4
    """Region defines an area that mobile nodes shall not enter"""
    REGION_TYPE_MOBILE_NODE_GO_AREA: Task.RegionType.ValueType  # 5
    """Region defines an area that mobile nodes shall remain within"""

    @_typing.final
    class Command(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        REQUEST_FIELD_NUMBER: _builtins.int
        DETECTION_THRESHOLD_FIELD_NUMBER: _builtins.int
        DETECTION_REPORT_RATE_FIELD_NUMBER: _builtins.int
        CLASSIFICATION_THRESHOLD_FIELD_NUMBER: _builtins.int
        MODE_CHANGE_FIELD_NUMBER: _builtins.int
        LOOK_AT_FIELD_NUMBER: _builtins.int
        MOVE_TO_FIELD_NUMBER: _builtins.int
        PATROL_FIELD_NUMBER: _builtins.int
        FOLLOW_FIELD_NUMBER: _builtins.int
        COMMAND_PARAMETER_FIELD_NUMBER: _builtins.int
        request: _builtins.str
        """The request being asked for"""
        detection_threshold: Global___Task.DiscreteThreshold.ValueType
        """The requested sensitivity of sensor during the task"""
        detection_report_rate: Global___Task.DiscreteThreshold.ValueType
        """The requested reporting rate of sensor during the task"""
        classification_threshold: Global___Task.DiscreteThreshold.ValueType
        """The requested classification sensitivity of sensor during the task"""
        mode_change: _builtins.str
        """Mode change for the ASM"""
        command_parameter: _builtins.str
        """Parameter string for some commands"""
        @_builtins.property
        def look_at(self) -> _range_bearing_pb2.LocationOrRangeBearing:
            """LookAt command for tasking pointing ASMs"""

        @_builtins.property
        def move_to(self) -> _location_pb2.LocationList:
            """command for instructing a mobile node to move to a new location"""

        @_builtins.property
        def patrol(self) -> _location_pb2.LocationList:
            """command for instructing a mobile node to continually patrol a route until instructed otherwise"""

        @_builtins.property
        def follow(self) -> _follow_pb2.FollowObject:
            """command for instructing a mobile node to follow a moving object until instructed otherwise"""

        def __init__(
            self,
            *,
            request: _builtins.str = ...,
            detection_threshold: Global___Task.DiscreteThreshold.ValueType = ...,
            detection_report_rate: Global___Task.DiscreteThreshold.ValueType = ...,
            classification_threshold: Global___Task.DiscreteThreshold.ValueType = ...,
            mode_change: _builtins.str = ...,
            look_at: _range_bearing_pb2.LocationOrRangeBearing | None = ...,
            move_to: _location_pb2.LocationList | None = ...,
            patrol: _location_pb2.LocationList | None = ...,
            follow: _follow_pb2.FollowObject | None = ...,
            command_parameter: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_command_parameter", b"_command_parameter", "classification_threshold", b"classification_threshold", "command", b"command", "command_parameter", b"command_parameter", "detection_report_rate", b"detection_report_rate", "detection_threshold", b"detection_threshold", "follow", b"follow", "look_at", b"look_at", "mode_change", b"mode_change", "move_to", b"move_to", "patrol", b"patrol", "request", b"request"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_command_parameter", b"_command_parameter", "classification_threshold", b"classification_threshold", "command", b"command", "command_parameter", b"command_parameter", "detection_report_rate", b"detection_report_rate", "detection_threshold", b"detection_threshold", "follow", b"follow", "look_at", b"look_at", "mode_change", b"mode_change", "move_to", b"move_to", "patrol", b"patrol", "request", b"request"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__command_parameter: _TypeAlias = _typing.Literal["command_parameter"]  # noqa: Y015
        _WhichOneofArgType__command_parameter: _TypeAlias = _typing.Literal["_command_parameter", b"_command_parameter"]  # noqa: Y015
        _WhichOneofReturnType_command: _TypeAlias = _typing.Literal["request", "detection_threshold", "detection_report_rate", "classification_threshold", "mode_change", "look_at", "move_to", "patrol", "follow"]  # noqa: Y015
        _WhichOneofArgType_command: _TypeAlias = _typing.Literal["command", b"command"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__command_parameter) -> _WhichOneofReturnType__command_parameter | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_command) -> _WhichOneofReturnType_command | None: ...

    @_typing.final
    class Region(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        REGION_ID_FIELD_NUMBER: _builtins.int
        REGION_NAME_FIELD_NUMBER: _builtins.int
        REGION_AREA_FIELD_NUMBER: _builtins.int
        CLASS_FILTER_FIELD_NUMBER: _builtins.int
        BEHAVIOUR_FILTER_FIELD_NUMBER: _builtins.int
        type: Global___Task.RegionType.ValueType
        """Type of region"""
        region_id: _builtins.str
        """Unique ID of region"""
        region_name: _builtins.str
        """Name of region"""
        @_builtins.property
        def region_area(self) -> _range_bearing_pb2.LocationOrRangeBearing:
            """Area that defines the region"""

        @_builtins.property
        def class_filter(self) -> _containers.RepeatedCompositeFieldContainer[Global___Task.ClassFilter]:
            """Filter for classifications detected in the region"""

        @_builtins.property
        def behaviour_filter(self) -> _containers.RepeatedCompositeFieldContainer[Global___Task.BehaviourFilter]:
            """Filter for behaviours detected in the region"""

        def __init__(
            self,
            *,
            type: Global___Task.RegionType.ValueType | None = ...,
            region_id: _builtins.str | None = ...,
            region_name: _builtins.str | None = ...,
            region_area: _range_bearing_pb2.LocationOrRangeBearing | None = ...,
            class_filter: _abc.Iterable[Global___Task.ClassFilter] | None = ...,
            behaviour_filter: _abc.Iterable[Global___Task.BehaviourFilter] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_region_area", b"_region_area", "_region_id", b"_region_id", "_region_name", b"_region_name", "_type", b"_type", "region_area", b"region_area", "region_id", b"region_id", "region_name", b"region_name", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_region_area", b"_region_area", "_region_id", b"_region_id", "_region_name", b"_region_name", "_type", b"_type", "behaviour_filter", b"behaviour_filter", "class_filter", b"class_filter", "region_area", b"region_area", "region_id", b"region_id", "region_name", b"region_name", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__region_area: _TypeAlias = _typing.Literal["region_area"]  # noqa: Y015
        _WhichOneofArgType__region_area: _TypeAlias = _typing.Literal["_region_area", b"_region_area"]  # noqa: Y015
        _WhichOneofReturnType__region_id: _TypeAlias = _typing.Literal["region_id"]  # noqa: Y015
        _WhichOneofArgType__region_id: _TypeAlias = _typing.Literal["_region_id", b"_region_id"]  # noqa: Y015
        _WhichOneofReturnType__region_name: _TypeAlias = _typing.Literal["region_name"]  # noqa: Y015
        _WhichOneofArgType__region_name: _TypeAlias = _typing.Literal["_region_name", b"_region_name"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__region_area) -> _WhichOneofReturnType__region_area | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__region_id) -> _WhichOneofReturnType__region_id | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__region_name) -> _WhichOneofReturnType__region_name | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class ClassFilter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PARAMETER_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        SUB_CLASS_FILTER_FIELD_NUMBER: _builtins.int
        PRIORITY_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """Type of classification to filter on"""
        priority: Global___Task.DiscreteThreshold.ValueType
        """Priority of filter"""
        @_builtins.property
        def parameter(self) -> Global___Task.Parameter:
            """Parameter to filter on"""

        @_builtins.property
        def sub_class_filter(self) -> _containers.RepeatedCompositeFieldContainer[Global___Task.SubClassFilter]:
            """Sub-classes to filter on"""

        def __init__(
            self,
            *,
            parameter: Global___Task.Parameter | None = ...,
            type: _builtins.str | None = ...,
            sub_class_filter: _abc.Iterable[Global___Task.SubClassFilter] | None = ...,
            priority: Global___Task.DiscreteThreshold.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "_priority", b"_priority", "_type", b"_type", "parameter", b"parameter", "priority", b"priority", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "_priority", b"_priority", "_type", b"_type", "parameter", b"parameter", "priority", b"priority", "sub_class_filter", b"sub_class_filter", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__parameter: _TypeAlias = _typing.Literal["parameter"]  # noqa: Y015
        _WhichOneofArgType__parameter: _TypeAlias = _typing.Literal["_parameter", b"_parameter"]  # noqa: Y015
        _WhichOneofReturnType__priority: _TypeAlias = _typing.Literal["priority"]  # noqa: Y015
        _WhichOneofArgType__priority: _TypeAlias = _typing.Literal["_priority", b"_priority"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__parameter) -> _WhichOneofReturnType__parameter | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__priority) -> _WhichOneofReturnType__priority | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class SubClassFilter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PARAMETER_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        SUB_CLASS_FILTER_FIELD_NUMBER: _builtins.int
        PRIORITY_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """Type of classification to filter on"""
        priority: Global___Task.DiscreteThreshold.ValueType
        """Priority of filter"""
        @_builtins.property
        def parameter(self) -> Global___Task.Parameter:
            """Parameter to filter on"""

        @_builtins.property
        def sub_class_filter(self) -> _containers.RepeatedCompositeFieldContainer[Global___Task.SubClassFilter]:
            """Sub-classes to filter on"""

        def __init__(
            self,
            *,
            parameter: Global___Task.Parameter | None = ...,
            type: _builtins.str | None = ...,
            sub_class_filter: _abc.Iterable[Global___Task.SubClassFilter] | None = ...,
            priority: Global___Task.DiscreteThreshold.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "_priority", b"_priority", "_type", b"_type", "parameter", b"parameter", "priority", b"priority", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "_priority", b"_priority", "_type", b"_type", "parameter", b"parameter", "priority", b"priority", "sub_class_filter", b"sub_class_filter", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__parameter: _TypeAlias = _typing.Literal["parameter"]  # noqa: Y015
        _WhichOneofArgType__parameter: _TypeAlias = _typing.Literal["_parameter", b"_parameter"]  # noqa: Y015
        _WhichOneofReturnType__priority: _TypeAlias = _typing.Literal["priority"]  # noqa: Y015
        _WhichOneofArgType__priority: _TypeAlias = _typing.Literal["_priority", b"_priority"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__parameter) -> _WhichOneofReturnType__parameter | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__priority) -> _WhichOneofReturnType__priority | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class BehaviourFilter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PARAMETER_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        PRIORITY_FIELD_NUMBER: _builtins.int
        type: _builtins.str
        """Type of behaviour to filter on"""
        priority: Global___Task.DiscreteThreshold.ValueType
        """Priority of filter"""
        @_builtins.property
        def parameter(self) -> Global___Task.Parameter:
            """Parameter to filter on"""

        def __init__(
            self,
            *,
            parameter: Global___Task.Parameter | None = ...,
            type: _builtins.str | None = ...,
            priority: Global___Task.DiscreteThreshold.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "_priority", b"_priority", "_type", b"_type", "parameter", b"parameter", "priority", b"priority", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "_priority", b"_priority", "_type", b"_type", "parameter", b"parameter", "priority", b"priority", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__parameter: _TypeAlias = _typing.Literal["parameter"]  # noqa: Y015
        _WhichOneofArgType__parameter: _TypeAlias = _typing.Literal["_parameter", b"_parameter"]  # noqa: Y015
        _WhichOneofReturnType__priority: _TypeAlias = _typing.Literal["priority"]  # noqa: Y015
        _WhichOneofArgType__priority: _TypeAlias = _typing.Literal["_priority", b"_priority"]  # noqa: Y015
        _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
        _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__parameter) -> _WhichOneofReturnType__parameter | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__priority) -> _WhichOneofReturnType__priority | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...

    @_typing.final
    class Parameter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        OPERATOR_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        """Name of the parameter to filter"""
        operator: _registration_pb2.Operator.ValueType
        """Operator to be filtered on"""
        value: _builtins.float
        """Threshold"""
        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            operator: _registration_pb2.Operator.ValueType | None = ...,
            value: _builtins.float | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_operator", b"_operator", "_value", b"_value", "name", b"name", "operator", b"operator", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_operator", b"_operator", "_value", b"_value", "name", b"name", "operator", b"operator", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
        _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
        _WhichOneofReturnType__operator: _TypeAlias = _typing.Literal["operator"]  # noqa: Y015
        _WhichOneofArgType__operator: _TypeAlias = _typing.Literal["_operator", b"_operator"]  # noqa: Y015
        _WhichOneofReturnType__value: _TypeAlias = _typing.Literal["value"]  # noqa: Y015
        _WhichOneofArgType__value: _TypeAlias = _typing.Literal["_value", b"_value"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__operator) -> _WhichOneofReturnType__operator | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__value) -> _WhichOneofReturnType__value | None: ...

    TASK_ID_FIELD_NUMBER: _builtins.int
    TASK_NAME_FIELD_NUMBER: _builtins.int
    TASK_DESCRIPTION_FIELD_NUMBER: _builtins.int
    TASK_START_TIME_FIELD_NUMBER: _builtins.int
    TASK_END_TIME_FIELD_NUMBER: _builtins.int
    CONTROL_FIELD_NUMBER: _builtins.int
    REGION_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """ULID for the task being sent"""
    task_name: _builtins.str
    """Name of the task being requested"""
    task_description: _builtins.str
    """Description of the task being requested"""
    control: Global___Task.Control.ValueType
    """Control action being requested"""
    @_builtins.property
    def task_start_time(self) -> _timestamp_pb2.Timestamp:
        """Time the task is requested to start at"""

    @_builtins.property
    def task_end_time(self) -> _timestamp_pb2.Timestamp:
        """Time the task is requested to end at"""

    @_builtins.property
    def region(self) -> _containers.RepeatedCompositeFieldContainer[Global___Task.Region]:
        """Area tasking is to be applied (such as a system implementing geo-fencing)"""

    @_builtins.property
    def command(self) -> Global___Task.Command:
        """Command being requested as part the task"""

    def __init__(
        self,
        *,
        task_id: _builtins.str | None = ...,
        task_name: _builtins.str | None = ...,
        task_description: _builtins.str | None = ...,
        task_start_time: _timestamp_pb2.Timestamp | None = ...,
        task_end_time: _timestamp_pb2.Timestamp | None = ...,
        control: Global___Task.Control.ValueType | None = ...,
        region: _abc.Iterable[Global___Task.Region] | None = ...,
        command: Global___Task.Command | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_command", b"_command", "_control", b"_control", "_task_description", b"_task_description", "_task_end_time", b"_task_end_time", "_task_id", b"_task_id", "_task_name", b"_task_name", "_task_start_time", b"_task_start_time", "command", b"command", "control", b"control", "task_description", b"task_description", "task_end_time", b"task_end_time", "task_id", b"task_id", "task_name", b"task_name", "task_start_time", b"task_start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_command", b"_command", "_control", b"_control", "_task_description", b"_task_description", "_task_end_time", b"_task_end_time", "_task_id", b"_task_id", "_task_name", b"_task_name", "_task_start_time", b"_task_start_time", "command", b"command", "control", b"control", "region", b"region", "task_description", b"task_description", "task_end_time", b"task_end_time", "task_id", b"task_id", "task_name", b"task_name", "task_start_time", b"task_start_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__command: _TypeAlias = _typing.Literal["command"]  # noqa: Y015
    _WhichOneofArgType__command: _TypeAlias = _typing.Literal["_command", b"_command"]  # noqa: Y015
    _WhichOneofReturnType__control: _TypeAlias = _typing.Literal["control"]  # noqa: Y015
    _WhichOneofArgType__control: _TypeAlias = _typing.Literal["_control", b"_control"]  # noqa: Y015
    _WhichOneofReturnType__task_description: _TypeAlias = _typing.Literal["task_description"]  # noqa: Y015
    _WhichOneofArgType__task_description: _TypeAlias = _typing.Literal["_task_description", b"_task_description"]  # noqa: Y015
    _WhichOneofReturnType__task_end_time: _TypeAlias = _typing.Literal["task_end_time"]  # noqa: Y015
    _WhichOneofArgType__task_end_time: _TypeAlias = _typing.Literal["_task_end_time", b"_task_end_time"]  # noqa: Y015
    _WhichOneofReturnType__task_id: _TypeAlias = _typing.Literal["task_id"]  # noqa: Y015
    _WhichOneofArgType__task_id: _TypeAlias = _typing.Literal["_task_id", b"_task_id"]  # noqa: Y015
    _WhichOneofReturnType__task_name: _TypeAlias = _typing.Literal["task_name"]  # noqa: Y015
    _WhichOneofArgType__task_name: _TypeAlias = _typing.Literal["_task_name", b"_task_name"]  # noqa: Y015
    _WhichOneofReturnType__task_start_time: _TypeAlias = _typing.Literal["task_start_time"]  # noqa: Y015
    _WhichOneofArgType__task_start_time: _TypeAlias = _typing.Literal["_task_start_time", b"_task_start_time"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__command) -> _WhichOneofReturnType__command | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__control) -> _WhichOneofReturnType__control | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_description) -> _WhichOneofReturnType__task_description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_end_time) -> _WhichOneofReturnType__task_end_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_id) -> _WhichOneofReturnType__task_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_name) -> _WhichOneofReturnType__task_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__task_start_time) -> _WhichOneofReturnType__task_start_time | None: ...

Global___Task: _TypeAlias = Task  # noqa: Y015
