"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SpeedUnits:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SpeedUnitsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpeedUnits.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPEED_UNITS_UNSPECIFIED: _SpeedUnits.ValueType  # 0
    """Units not defined"""
    SPEED_UNITS_MS: _SpeedUnits.ValueType  # 1
    """Meters per second"""
    SPEED_UNITS_KPH: _SpeedUnits.ValueType  # 2
    """Kilometers per hour"""

class SpeedUnits(_SpeedUnits, metaclass=_SpeedUnitsEnumTypeWrapper):
    """This specifies the units of the scalar speed component of velocity being reported"""

SPEED_UNITS_UNSPECIFIED: SpeedUnits.ValueType  # 0
"""Units not defined"""
SPEED_UNITS_MS: SpeedUnits.ValueType  # 1
"""Meters per second"""
SPEED_UNITS_KPH: SpeedUnits.ValueType  # 2
"""Kilometers per hour"""
Global___SpeedUnits: _TypeAlias = SpeedUnits  # noqa: Y015

@_typing.final
class ENUVelocity(_message.Message):
    """[START messages]

    Provide velocity as a vector in global cartesian coordinates
    This is a revision of the TIE22 LocationVelocity encoding velocity as per the Location field but with eastings, northings and up for clarity.
    This aligns with the Location (Cartesian) coordinates system.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EAST_RATE_FIELD_NUMBER: _builtins.int
    NORTH_RATE_FIELD_NUMBER: _builtins.int
    UP_RATE_FIELD_NUMBER: _builtins.int
    EAST_RATE_ERROR_FIELD_NUMBER: _builtins.int
    NORTH_RATE_ERROR_FIELD_NUMBER: _builtins.int
    UP_RATE_ERROR_FIELD_NUMBER: _builtins.int
    east_rate: _builtins.float
    """Velocity in the east-axis (x)"""
    north_rate: _builtins.float
    """Velocity in the north-axis (y)"""
    up_rate: _builtins.float
    """Velocity in the up-axis (z)"""
    east_rate_error: _builtins.float
    """Error in the velocity in the east-axis"""
    north_rate_error: _builtins.float
    """Error in the velocity in the north-axis"""
    up_rate_error: _builtins.float
    """Error in the velocity in the up-axis"""
    def __init__(
        self,
        *,
        east_rate: _builtins.float | None = ...,
        north_rate: _builtins.float | None = ...,
        up_rate: _builtins.float | None = ...,
        east_rate_error: _builtins.float | None = ...,
        north_rate_error: _builtins.float | None = ...,
        up_rate_error: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_east_rate", b"_east_rate", "_east_rate_error", b"_east_rate_error", "_north_rate", b"_north_rate", "_north_rate_error", b"_north_rate_error", "_up_rate", b"_up_rate", "_up_rate_error", b"_up_rate_error", "east_rate", b"east_rate", "east_rate_error", b"east_rate_error", "north_rate", b"north_rate", "north_rate_error", b"north_rate_error", "up_rate", b"up_rate", "up_rate_error", b"up_rate_error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_east_rate", b"_east_rate", "_east_rate_error", b"_east_rate_error", "_north_rate", b"_north_rate", "_north_rate_error", b"_north_rate_error", "_up_rate", b"_up_rate", "_up_rate_error", b"_up_rate_error", "east_rate", b"east_rate", "east_rate_error", b"east_rate_error", "north_rate", b"north_rate", "north_rate_error", b"north_rate_error", "up_rate", b"up_rate", "up_rate_error", b"up_rate_error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__east_rate: _TypeAlias = _typing.Literal["east_rate"]  # noqa: Y015
    _WhichOneofArgType__east_rate: _TypeAlias = _typing.Literal["_east_rate", b"_east_rate"]  # noqa: Y015
    _WhichOneofReturnType__east_rate_error: _TypeAlias = _typing.Literal["east_rate_error"]  # noqa: Y015
    _WhichOneofArgType__east_rate_error: _TypeAlias = _typing.Literal["_east_rate_error", b"_east_rate_error"]  # noqa: Y015
    _WhichOneofReturnType__north_rate: _TypeAlias = _typing.Literal["north_rate"]  # noqa: Y015
    _WhichOneofArgType__north_rate: _TypeAlias = _typing.Literal["_north_rate", b"_north_rate"]  # noqa: Y015
    _WhichOneofReturnType__north_rate_error: _TypeAlias = _typing.Literal["north_rate_error"]  # noqa: Y015
    _WhichOneofArgType__north_rate_error: _TypeAlias = _typing.Literal["_north_rate_error", b"_north_rate_error"]  # noqa: Y015
    _WhichOneofReturnType__up_rate: _TypeAlias = _typing.Literal["up_rate"]  # noqa: Y015
    _WhichOneofArgType__up_rate: _TypeAlias = _typing.Literal["_up_rate", b"_up_rate"]  # noqa: Y015
    _WhichOneofReturnType__up_rate_error: _TypeAlias = _typing.Literal["up_rate_error"]  # noqa: Y015
    _WhichOneofArgType__up_rate_error: _TypeAlias = _typing.Literal["_up_rate_error", b"_up_rate_error"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__east_rate) -> _WhichOneofReturnType__east_rate | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__east_rate_error) -> _WhichOneofReturnType__east_rate_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__north_rate) -> _WhichOneofReturnType__north_rate | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__north_rate_error) -> _WhichOneofReturnType__north_rate_error | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__up_rate) -> _WhichOneofReturnType__up_rate | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__up_rate_error) -> _WhichOneofReturnType__up_rate_error | None: ...

Global___ENUVelocity: _TypeAlias = ENUVelocity  # noqa: Y015

@_typing.final
class ENUVelocityUnits(_message.Message):
    """Specify units when ENUVelocity is in use"""

    DESCRIPTOR: _descriptor.Descriptor

    EAST_NORTH_RATE_UNITS_FIELD_NUMBER: _builtins.int
    UP_RATE_UNITS_FIELD_NUMBER: _builtins.int
    east_north_rate_units: Global___SpeedUnits.ValueType
    """Units that velocity is reported in for east and north axis"""
    up_rate_units: Global___SpeedUnits.ValueType
    """Units that velocity is reported in for up axis"""
    def __init__(
        self,
        *,
        east_north_rate_units: Global___SpeedUnits.ValueType | None = ...,
        up_rate_units: Global___SpeedUnits.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_east_north_rate_units", b"_east_north_rate_units", "_up_rate_units", b"_up_rate_units", "east_north_rate_units", b"east_north_rate_units", "up_rate_units", b"up_rate_units"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_east_north_rate_units", b"_east_north_rate_units", "_up_rate_units", b"_up_rate_units", "east_north_rate_units", b"east_north_rate_units", "up_rate_units", b"up_rate_units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__east_north_rate_units: _TypeAlias = _typing.Literal["east_north_rate_units"]  # noqa: Y015
    _WhichOneofArgType__east_north_rate_units: _TypeAlias = _typing.Literal["_east_north_rate_units", b"_east_north_rate_units"]  # noqa: Y015
    _WhichOneofReturnType__up_rate_units: _TypeAlias = _typing.Literal["up_rate_units"]  # noqa: Y015
    _WhichOneofArgType__up_rate_units: _TypeAlias = _typing.Literal["_up_rate_units", b"_up_rate_units"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__east_north_rate_units) -> _WhichOneofReturnType__east_north_rate_units | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__up_rate_units) -> _WhichOneofReturnType__up_rate_units | None: ...

Global___ENUVelocityUnits: _TypeAlias = ENUVelocityUnits  # noqa: Y015
