"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dstl (c) Crown Copyright 2024

[START declaration]
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FileOptions(_message.Message):
    """[START messages]"""

    DESCRIPTOR: _descriptor.Descriptor

    STANDARD_VERSION_FIELD_NUMBER: _builtins.int
    standard_version: _builtins.str
    def __init__(
        self,
        *,
        standard_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["standard_version", b"standard_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileOptions: _TypeAlias = FileOptions  # noqa: Y015

@_typing.final
class ValidationOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IS_MANDATORY_FIELD_NUMBER: _builtins.int
    IS_ULID_FIELD_NUMBER: _builtins.int
    IS_UUID_FIELD_NUMBER: _builtins.int
    XML_NAME_FIELD_NUMBER: _builtins.int
    XML_IS_ATTRIBUTE_FIELD_NUMBER: _builtins.int
    XML_IGNORE_FIELD_NUMBER: _builtins.int
    XML_SINGLY_NESTED_FIELD_NUMBER: _builtins.int
    XML_IS_PARENT_VALUE_FIELD_NUMBER: _builtins.int
    ENUM_NAME_FIELD_NUMBER: _builtins.int
    IS_PROTO_TIME_FIELD_NUMBER: _builtins.int
    XML_TENTATIVE_FIELD_NUMBER: _builtins.int
    IS_TIME_FIELD_NUMBER: _builtins.int
    is_mandatory: _builtins.bool
    is_ulid: _builtins.bool
    is_uuid: _builtins.bool
    xml_name: _builtins.str
    xml_is_attribute: _builtins.bool
    xml_ignore: _builtins.bool
    xml_singly_nested: _builtins.str
    xml_is_parent_value: _builtins.bool
    enum_name: _builtins.str
    is_proto_time: _builtins.bool
    xml_tentative: _builtins.bool
    is_time: _builtins.bool
    def __init__(
        self,
        *,
        is_mandatory: _builtins.bool | None = ...,
        is_ulid: _builtins.bool | None = ...,
        is_uuid: _builtins.bool | None = ...,
        xml_name: _builtins.str | None = ...,
        xml_is_attribute: _builtins.bool | None = ...,
        xml_ignore: _builtins.bool | None = ...,
        xml_singly_nested: _builtins.str | None = ...,
        xml_is_parent_value: _builtins.bool | None = ...,
        enum_name: _builtins.str | None = ...,
        is_proto_time: _builtins.bool | None = ...,
        xml_tentative: _builtins.bool | None = ...,
        is_time: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enum_name", b"_enum_name", "_is_mandatory", b"_is_mandatory", "_is_proto_time", b"_is_proto_time", "_is_time", b"_is_time", "_is_ulid", b"_is_ulid", "_is_uuid", b"_is_uuid", "_xml_ignore", b"_xml_ignore", "_xml_is_attribute", b"_xml_is_attribute", "_xml_is_parent_value", b"_xml_is_parent_value", "_xml_name", b"_xml_name", "_xml_singly_nested", b"_xml_singly_nested", "_xml_tentative", b"_xml_tentative", "enum_name", b"enum_name", "is_mandatory", b"is_mandatory", "is_proto_time", b"is_proto_time", "is_time", b"is_time", "is_ulid", b"is_ulid", "is_uuid", b"is_uuid", "xml_ignore", b"xml_ignore", "xml_is_attribute", b"xml_is_attribute", "xml_is_parent_value", b"xml_is_parent_value", "xml_name", b"xml_name", "xml_singly_nested", b"xml_singly_nested", "xml_tentative", b"xml_tentative"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enum_name", b"_enum_name", "_is_mandatory", b"_is_mandatory", "_is_proto_time", b"_is_proto_time", "_is_time", b"_is_time", "_is_ulid", b"_is_ulid", "_is_uuid", b"_is_uuid", "_xml_ignore", b"_xml_ignore", "_xml_is_attribute", b"_xml_is_attribute", "_xml_is_parent_value", b"_xml_is_parent_value", "_xml_name", b"_xml_name", "_xml_singly_nested", b"_xml_singly_nested", "_xml_tentative", b"_xml_tentative", "enum_name", b"enum_name", "is_mandatory", b"is_mandatory", "is_proto_time", b"is_proto_time", "is_time", b"is_time", "is_ulid", b"is_ulid", "is_uuid", b"is_uuid", "xml_ignore", b"xml_ignore", "xml_is_attribute", b"xml_is_attribute", "xml_is_parent_value", b"xml_is_parent_value", "xml_name", b"xml_name", "xml_singly_nested", b"xml_singly_nested", "xml_tentative", b"xml_tentative"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enum_name: _TypeAlias = _typing.Literal["enum_name"]  # noqa: Y015
    _WhichOneofArgType__enum_name: _TypeAlias = _typing.Literal["_enum_name", b"_enum_name"]  # noqa: Y015
    _WhichOneofReturnType__is_mandatory: _TypeAlias = _typing.Literal["is_mandatory"]  # noqa: Y015
    _WhichOneofArgType__is_mandatory: _TypeAlias = _typing.Literal["_is_mandatory", b"_is_mandatory"]  # noqa: Y015
    _WhichOneofReturnType__is_proto_time: _TypeAlias = _typing.Literal["is_proto_time"]  # noqa: Y015
    _WhichOneofArgType__is_proto_time: _TypeAlias = _typing.Literal["_is_proto_time", b"_is_proto_time"]  # noqa: Y015
    _WhichOneofReturnType__is_time: _TypeAlias = _typing.Literal["is_time"]  # noqa: Y015
    _WhichOneofArgType__is_time: _TypeAlias = _typing.Literal["_is_time", b"_is_time"]  # noqa: Y015
    _WhichOneofReturnType__is_ulid: _TypeAlias = _typing.Literal["is_ulid"]  # noqa: Y015
    _WhichOneofArgType__is_ulid: _TypeAlias = _typing.Literal["_is_ulid", b"_is_ulid"]  # noqa: Y015
    _WhichOneofReturnType__is_uuid: _TypeAlias = _typing.Literal["is_uuid"]  # noqa: Y015
    _WhichOneofArgType__is_uuid: _TypeAlias = _typing.Literal["_is_uuid", b"_is_uuid"]  # noqa: Y015
    _WhichOneofReturnType__xml_ignore: _TypeAlias = _typing.Literal["xml_ignore"]  # noqa: Y015
    _WhichOneofArgType__xml_ignore: _TypeAlias = _typing.Literal["_xml_ignore", b"_xml_ignore"]  # noqa: Y015
    _WhichOneofReturnType__xml_is_attribute: _TypeAlias = _typing.Literal["xml_is_attribute"]  # noqa: Y015
    _WhichOneofArgType__xml_is_attribute: _TypeAlias = _typing.Literal["_xml_is_attribute", b"_xml_is_attribute"]  # noqa: Y015
    _WhichOneofReturnType__xml_is_parent_value: _TypeAlias = _typing.Literal["xml_is_parent_value"]  # noqa: Y015
    _WhichOneofArgType__xml_is_parent_value: _TypeAlias = _typing.Literal["_xml_is_parent_value", b"_xml_is_parent_value"]  # noqa: Y015
    _WhichOneofReturnType__xml_name: _TypeAlias = _typing.Literal["xml_name"]  # noqa: Y015
    _WhichOneofArgType__xml_name: _TypeAlias = _typing.Literal["_xml_name", b"_xml_name"]  # noqa: Y015
    _WhichOneofReturnType__xml_singly_nested: _TypeAlias = _typing.Literal["xml_singly_nested"]  # noqa: Y015
    _WhichOneofArgType__xml_singly_nested: _TypeAlias = _typing.Literal["_xml_singly_nested", b"_xml_singly_nested"]  # noqa: Y015
    _WhichOneofReturnType__xml_tentative: _TypeAlias = _typing.Literal["xml_tentative"]  # noqa: Y015
    _WhichOneofArgType__xml_tentative: _TypeAlias = _typing.Literal["_xml_tentative", b"_xml_tentative"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enum_name) -> _WhichOneofReturnType__enum_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_mandatory) -> _WhichOneofReturnType__is_mandatory | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_proto_time) -> _WhichOneofReturnType__is_proto_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_time) -> _WhichOneofReturnType__is_time | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_ulid) -> _WhichOneofReturnType__is_ulid | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_uuid) -> _WhichOneofReturnType__is_uuid | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_ignore) -> _WhichOneofReturnType__xml_ignore | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_is_attribute) -> _WhichOneofReturnType__xml_is_attribute | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_is_parent_value) -> _WhichOneofReturnType__xml_is_parent_value | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_name) -> _WhichOneofReturnType__xml_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_singly_nested) -> _WhichOneofReturnType__xml_singly_nested | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_tentative) -> _WhichOneofReturnType__xml_tentative | None: ...

Global___ValidationOptions: _TypeAlias = ValidationOptions  # noqa: Y015

@_typing.final
class MessageOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    XML_MESSAGE_NAME_FIELD_NUMBER: _builtins.int
    IS_SAPIENT_MESSAGE_FIELD_NUMBER: _builtins.int
    xml_message_name: _builtins.str
    is_sapient_message: _builtins.bool
    def __init__(
        self,
        *,
        xml_message_name: _builtins.str | None = ...,
        is_sapient_message: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_is_sapient_message", b"_is_sapient_message", "_xml_message_name", b"_xml_message_name", "is_sapient_message", b"is_sapient_message", "xml_message_name", b"xml_message_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_is_sapient_message", b"_is_sapient_message", "_xml_message_name", b"_xml_message_name", "is_sapient_message", b"is_sapient_message", "xml_message_name", b"xml_message_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__is_sapient_message: _TypeAlias = _typing.Literal["is_sapient_message"]  # noqa: Y015
    _WhichOneofArgType__is_sapient_message: _TypeAlias = _typing.Literal["_is_sapient_message", b"_is_sapient_message"]  # noqa: Y015
    _WhichOneofReturnType__xml_message_name: _TypeAlias = _typing.Literal["xml_message_name"]  # noqa: Y015
    _WhichOneofArgType__xml_message_name: _TypeAlias = _typing.Literal["_xml_message_name", b"_xml_message_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_sapient_message) -> _WhichOneofReturnType__is_sapient_message | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__xml_message_name) -> _WhichOneofReturnType__xml_message_name | None: ...

Global___MessageOptions: _TypeAlias = MessageOptions  # noqa: Y015

FILE_OPTIONS_FIELD_NUMBER: _builtins.int
ENUM_OPTIONS_FIELD_NUMBER: _builtins.int
ONEOF_OPTIONS_FIELD_NUMBER: _builtins.int
FIELD_OPTIONS_FIELD_NUMBER: _builtins.int
MESSAGE_OPTIONS_FIELD_NUMBER: _builtins.int
file_options: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, Global___FileOptions]
enum_options: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, Global___ValidationOptions]
oneof_options: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.OneofOptions, Global___ValidationOptions]
field_options: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, Global___ValidationOptions]
message_options: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, Global___MessageOptions]
